automerge/automerge

automerge-backend-wasm/columnar.js
automerge-backend-wasm/encoding.js
automerge-backend-wasm/index.js
automerge-backend-wasm/src/lib.rs

Intended to go with automerge/automerge@6c17526cec9712488e8820083bf0cbc5a36fc71e and preceding commits. These commits allow the backend to be swapped out, remove dependency on immutability, and clean up the API so that code outside of the backend doesn't reach directly into backend internals.
Currently the tests still throw a lot of errors like:
"serde_json error: invalid type: null, expected a map at line 1 column 4"
Not sure where they are coming from as it's not showing a stack trace.

Update to match Automerge performance branch

---

automerge-frontend/tests/test_frontend.rs
automerge-protocol/src/lib.rs

Ran into this issue when using `Frontend::new_with_initial_state` where it would panic when it was trying to decode a bare UUID as a hex-encoded string.

protocol: Hex-encode random ActorID

---

automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/columnar.rs
automerge-backend/src/object_store.rs
automerge-backend/src/op.rs
automerge-backend/src/op_set.rs
automerge-backend/src/op_type.rs
automerge-backend/tests/apply_change.rs
automerge-backend/tests/apply_local_change.rs
automerge-backend/tests/get_patch.rs
automerge-frontend/src/change_context.rs
automerge-frontend/src/lib.rs
automerge-frontend/src/mutation.rs
automerge-frontend/src/object.rs
automerge-frontend/src/value.rs
automerge-frontend/tests/test_apply_patch.rs
automerge-frontend/tests/test_backend_concurrency.rs
automerge-frontend/tests/test_frontend.rs
automerge-protocol/Cargo.toml
automerge-protocol/src/lib.rs
automerge-protocol/src/serde_impls/diff.rs

This changes the `ObjType` enum from 
```
enum ObjType {
Map,
List,
Table,
Text
}
```
to 
```
enum ObjType {
Map(MapType),
Sequence(SequenceType)
}
enum MapType {
Map,
Table,
}
enum SequenceType {
List
Text,
}
```
The serde serialization of diffs remains the same so there's no FFI change.
The main reason to do this is that it allows a greater degree of type safety when processing `MapDiff` and `SeqDiff`. This is because we can now set the `obj_type` of each diff to `MapType` and `SequenceType` respectively, which means that we have less panicky match arms in the frontend codebase.

Two level objtype

---

automerge-backend-wasm/index.js
automerge-backend-wasm/test/backend_test.js
automerge-backend/src/change.rs
automerge-backend/src/columnar.rs
automerge-backend/src/encoding.rs
automerge-backend/src/op.rs
automerge-c/automerge.c
automerge-frontend/src/mutation.rs
automerge-frontend/tests/test_frontend.rs
automerge-protocol/src/lib.rs
automerge-protocol/src/serde_impls/object_id.rs
automerge-protocol/src/utility_impls/object_id.rs

This PR is the Rust counterpart to automerge/automerge#296. The individual commits on this PR link to their counterparts in the JS implementation.
Due to my poor Rust skills I couldn't figure out how to write the Rust counterpart for automerge/automerge@6fa8b5a5b9bbfb178750c629fc6107b30b9c35a3, so that change is missing from this PR. Could one of you please help with that? If you check out the predecessor commit automerge/automerge@7f2e9f4897a420ca6ebd36421e935dc09484d1d4 on the JS repo, and compile d320ba8b23fc7e0aa2501f4ff98feffcd32d4e98 on this repo, the JS-Wasm tests should be passing, so this PR should only be missing the Rust counterpart to automerge/automerge@6fa8b5a5b9bbfb178750c629fc6107b30b9c35a3.
Commit d320ba8b23fc7e0aa2501f4ff98feffcd32d4e98 is incomplete: although `yarn …

Tweaks to data formats

---

README.md

This PR refactors the javascript word to the Upper Camel case, making it more precise.

Refactored javascript into JavaScript

---

automerge-frontend/Cargo.toml
automerge-frontend/src/lib.rs

Fixes https://github.com/automerge/automerge-rs/issues/50
I've gone with using a `Box` rather than a type variable on the `Frontend` struct to maintain compatibility with existing code.
Also had to manually implement `Debug` for `Frontend` since the `timestamper` doesn't implement it.

Nostd time

---

automerge-backend-wasm/Cargo.toml

Some js/wasm features need to be enabled for `getrandom` and `uuid` to ensure that they compile ok when targetting the `wasm32-unknown-unknown` target.

backend-wasm: Make yarn release work again

---

.travis.yml
README.md

I've added some extra bits to the travis config for testing the build of the wasm backend and also added some folds to make the output easier to inspect.
I've also updated the build badge in the readme to use the `main` branch instead of `master`.

Update travis config

---

automerge-backend/src/columnar.rs
automerge-backend/src/encoding.rs
automerge-frontend/src/lib.rs
automerge/Cargo.toml
automerge/tests/save_load.rs

I've managed to hunt down this bug with another more reliable test case and found that the RLE decoder was reading the length of the null run as `isize` when it is encoded as `usize`. This becomes an issue when the length is above a certain value (64 here). Then the length gets read as negative and the decoder enters an infinite loop of repeating the null value, even when there is more input.
Maybe in future we shouldn't use `*size` either but `*64` or `*32` explicitly so different platforms don't have issues saving/loading shared documents. I'll leave that for another time.
Fixes #57

Fix issue in RleDecoder with null runs

---

.travis.yml
automerge-frontend/Cargo.toml
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/tests/test_wasm.rs

Fixes #54.
This makes the contents of the Vector satisfy the alignment rules required by the inner logic on 32 bit architectures.
The test also triggers this issue without the fix so should serve to detect it in future.
While it might not be ideal to have the added layer of indirection here I'm not aware of another alternative without digging further into the dependency but this fixes it nicely.

Fix alignment error on wasm32

---

automerge-frontend/Cargo.toml
automerge-frontend/src/mutation.rs
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/multivalue.rs
automerge-frontend/src/state_tree/resolved_path.rs
automerge-frontend/src/value.rs
automerge-frontend/tests/test_apply_patch.rs
automerge-frontend/tests/test_cursor.rs
automerge-frontend/tests/test_frontend.rs
automerge/Cargo.toml
automerge/tests/text_grapheme_clusters.rs

`char` is not what users typically expect as a 'letter' so we should use
grapheme clusters instead. These can't always be represented as single
rust `char` types so the `Text` now stores a `Vec` of single grapheme `String`s.
Fixes #44 
While this makes sense from the rust side I'm not sure if it has an effect on the javascript implementation compatability. Also, not sure of its affect on the binary encoding from the javascript side again.

Use grapheme clusters in Text instead of char

---

automerge-backend/src/backend.rs
automerge-backend/src/lib.rs
automerge-backend/src/object_store.rs
automerge-backend/src/op_handle.rs
automerge-backend/src/op_set.rs
automerge-c/src/lib.rs
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/tests/test_backend_concurrency.rs
automerge/benches/crdt_benchmarks.rs
automerge/src/lib.rs

This mechanically removes `Rc` from the backend code. There weren't any major issues so it seems as though it wasn't needed.
If someone has more knowledge on why it was needed I'd be happy to hear.
Fixes #75

Remove Rc from the backend

---

automerge-backend/src/backend.rs

A few nits, caught my attention when looking at https://github.com/automerge/automerge-rs/pull/78

Backend: remove unnecessary draining of changes to be applied

---

automerge-backend-wasm/src/lib.rs

Fixes #81. The JS backend now exposes a function `Backend.getAllChanges(backend)`, which is currently just a shortcut for `Backend.getChanges(backend, [])` but which may have a more optimised implementation in the future.
Also removed `Backend.getChangesForActor`, which no longer exists in the JS backend. I think the corresponding `get_changes_for_actor` could also be removed from `automerge-c/src/lib.rs` and `automerge-backend/src/backend.rs`, but the function is currently still used by `automerge-c/automerge.c` so I left it there for now.

Add getAllChanges function to wasm backend

---

automerge-backend/src/backend.rs
automerge-backend/src/sync.rs

This means we no longer need to store an unbounded list of hashes while
syncing. This is possible as we know their heads and all changes we send
should be known to us, thus we can look in our history to see whether
they are safely applied at the other end.

Filter sent hashes down to only what they haven't seen

---

automerge-backend/src/columnar.rs
automerge-backend/src/encoding.rs

For `encode` being the basic operation of the `Encodable` trait it seems strange to have it be default implementable. I think this could ultimately lead to more annoyances than writing the default explanation where we don't want it to actually encode, e.g. with `ActorId`s. It also encourages to document why the encoding is different for those special cases.

encodable: Require encode function implementation

---

automerge-backend-wasm/Cargo.toml
automerge-backend/Cargo.toml
automerge-c/Cargo.toml
automerge-cli/Cargo.toml
automerge-frontend/Cargo.toml
automerge-protocol/Cargo.toml

This removes the default wrapper which throws errors with some cli
arguments, e.g. --save-baseline which is nice for being able to compare
versions!

Remove automerge bench harness

---

automerge-backend/src/actor_map.rs
automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/columnar.rs
automerge-backend/src/encoding.rs
automerge-backend/src/lib.rs
automerge-backend/src/object_store.rs
automerge-backend/src/op_handle.rs
automerge-backend/src/op_set.rs
automerge-backend/src/ordered_set.rs
automerge-backend/src/pending_diff.rs
automerge-backend/src/sync.rs
automerge-backend/src/sync/bloom.rs

Move to storing changes only in the history to reduce duplication and some other style cleanups. Also introduced some more clippy linting and I've disabled some annoying lints but find that it does improve the code further and we can always re-enable them later.
Happy to discuss things / update clippy rules. May be best to look commit-by-commit.

Backend tidy

---

automerge-frontend/Cargo.toml
automerge-frontend/src/value.rs
automerge-protocol/Cargo.toml
automerge-protocol/src/lib.rs

This makes it possible to use a fuzzer to generate `Value` types among others. This is useful when we can generate these and feed them into something like `frontend.change(...)`.
Its behind a feature since most people won't need it on so only pull in the dependency and build the code when explicitly asked.

Add derive Arbitrary support behind cargo feature

---

automerge-backend/src/backend.rs

This helps to avoid traversing the entire graph when we get a successive
change that we know can't be a predecessor of the heads.
Also `filter_changes` shouldn't be globally public.

Improve filter_changes for sync

---

automerge-backend-wasm/src/lib.rs
automerge-backend/src/actor_map.rs
automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/lib.rs
automerge-backend/src/op_set.rs
automerge-backend/tests/apply_change.rs
automerge-backend/tests/apply_local_change.rs
automerge-backend/tests/get_changes.rs
automerge-backend/tests/get_patch.rs
automerge-c/src/lib.rs
automerge-cli/src/change.rs
automerge-cli/src/export.rs
automerge-cli/src/import.rs
automerge-frontend/tests/test_backend_concurrency.rs
automerge-frontend/tests/test_cursor.rs
automerge/benches/crdt_benchmarks.rs
automerge/benches/save_load.rs
automerge/benches/sync.rs
automerge/tests/save_load.rs
automerge/tests/text_grapheme_clusters.rs

Structs should use `new` for the constructor name and implement
`Default` where they can.
This keeps the `init` function exposed to wasm and C for the backend.

Change init to new and add defaults

---

automerge-backend/src/lib.rs

Missed this, it is opaque but people may want to use it in signatures.

Expose event handler id

---

automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/resolved_path.rs
automerge/tests/frontend_backend_roundtrip.rs

Element ids in sequences are tied to the operation that created the element. Performing a set shouldn't update the element id as it was previously doing. This was from a test case found by quickcheck in automergeable.

Use elem id from insertion in frontend

---

automerge-c/automerge.c
automerge-c/automerge.h
automerge-c/src/lib.rs

Follow-up to the PR implementing C-bindings for sync state.
There seems to be 1 issue (can't tell if it's an issue really), where the assert at the end of the new test fails (`len == 7` not `len == 0`). I'm not sure if this is b/c the test is incorrect or the bindings are incorrect.
My guess is the test is incorrect.
Also the sync state serializes to 2 byes in the test which seems really small?

Implement encode/decode for SyncState

---

automerge-frontend/src/lib.rs
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/multivalue.rs
automerge/tests/frontend_backend_roundtrip.rs

Was failing with `MismatchedSequenceNumber { expected: 1, actual: 2 }`
Now fixed!

Add mismatched sequence number failing test

---

.travis.yml

This splits the `script` up into separate jobs. I find it very hard to find a failure on travis when all of the output is in one file. This helps to break it down to some related jobs. Keeping some bits together avoids recompilation, e.g. build then test. This can also help with overall feedback time as jobs can fail before others (e.g. clippy fails before build completes).
Happy to discuss if there are any other ideas :)
Since this makes things (at least seem) a bit quicker we could get away without the complexity of managing a cache.

Refactor travis to have more jobs

---

Cargo.toml
automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/decoding.rs
automerge-backend/tests/load.rs
flake.nix
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/src/backend_load.rs

This adds some fuzzing to check loading arbitrary bytes. While these shouldn't always generate actual values it shouldn't panic.
The fuzzing found some issues that I've encapsulated in tests and fixed.

Fix backend panics

---

automerge-backend/src/decoding.rs
automerge-backend/src/encoding.rs
automerge-backend/src/lib.rs

Fixes https://github.com/automerge/automerge-rs/issues/143
This makes the errors public and usable by consumers of the API.
Up to discussing whether we want to keep a flat API or nested?

Make encoding and decoding mods public for errors

---

automerge-c/Cargo.toml
automerge-cli/Cargo.toml

This gives an error due to the duplicate name.
Avoids
```
error: The library `automerge` is specified by packages `automerge v0.0.2 (/home/$USER/projects/automerge-rs/automerge)` and `automerge-c v0.1.0 (/home/$USER/projects/automerge-rs/automerge-c)` but can only be documented once. Consider renaming or marking one of the targets as `doc = false`.
```
The CLI similarly has a name conflict with the automerge library and generates a warning.

Dont document the C lib and CLI

---

automerge-backend-wasm/src/lib.rs

This means we can get nicer panic messages in the JS side when using the wasm backend.
This was already in the `Cargo.toml` so I expect it was there at some point in history in the code too but I don't know what happened to it.
Ideally we wouldn't ever panic but especially as this is still under development with things breaking it will at least make debugging wasm tests a bit easier.
We could also add it in more places, e.g. where we create sync states but I think the backend is the main place.

Set console_error_panic_hook when initing a backend

---

automerge-frontend/src/state_tree/diffable_sequence.rs

These were likely used at one point but now just incur an expensive
allocation cost. This reduces the B1.1 Append N characters benchmark
from ~19s to ~16s.

Remove unused variables in diffable sequence

---

automerge-backend/src/change.rs

found a place with in document loads that was bottlenecking - sped it up with a binary search.  Also did some code cleanup for easier reading.

added binary search to doc decode for big speedup

---

automerge-frontend/src/lib.rs
automerge-frontend/tests/test_cursor.rs

This has the same functionality as get_value and we only need one.
We can always rename `get_value` another time but we don't need both of these.

Remove value_at_path

---

automerge-frontend/src/lib.rs
automerge-frontend/src/mutation.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/multivalue.rs
automerge-frontend/src/value.rs
automerge-frontend/tests/test_apply_patch.rs
automerge-frontend/tests/test_frontend.rs
automerge/benches/crdt_benchmarks.rs
automerge/benches/save_load.rs
automerge/tests/frontend_backend_roundtrip.rs
automerge/tests/save_load.rs
automerge/tests/text_grapheme_clusters.rs
perf/src/main.rs

This simplifies the `Value` enum and hides the protocol internals from the
variants.
Fixes #158

Remove MapType from Map and add Table variant

---

automerge-backend/src/columnar.rs
automerge-backend/src/object_store.rs
automerge-backend/src/op_set.rs

These shouldn't be reported for user applications and are more just for our own debugging.

Set levels for instrument

---

automerge-backend-wasm/src/lib.rs
automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/columnar.rs
automerge-backend/tests/apply_change.rs
automerge-backend/tests/apply_local_change.rs
automerge-backend/tests/get_patch.rs
automerge-c-v2/src/lib.rs
automerge-c/src/lib.rs
automerge-cli/src/examine.rs
automerge-frontend/src/lib.rs
automerge-frontend/tests/test_backend_concurrency.rs
automerge-frontend/tests/test_frontend.rs
automerge-frontend/tests/test_mutation.rs
automerge-protocol/src/lib.rs
automerge-protocol/tests/serde_round_trip_proptest.rs
automerge/tests/frontend_backend_roundtrip.rs
automerge/tests/save_load.rs

It wasn't really uncompressed as we have compressed and uncompressed
changes in the backend. It is just not encoded into the binary format.
The module separation (protocol vs backend) should help with the
distinction.
Fixes #114

Rename UncompressedChange to Change

---

automerge-frontend/src/lib.rs
automerge-frontend/src/mutation.rs
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/multivalue.rs
automerge-frontend/src/state_tree/resolved_path.rs

This implements rollback on a `MutableDocument`. This is useful to handle when the user applies a change to the document that causes an error (e.g. missing index in insert). This mainly avoids us having to clone the current state each time and lets us make the hot path quicker and cheaper.
Thankfully when we overwrite a value in the document (map or seq), including deletes, we get the old value back so we can get away with not having to clone things and this ends up just delaying the drop call until we have finished with all of our changes.
tldr: cloning a large document for each change is expensive, tracking the individual changes for rollback is much cheaper

Mutation tracker rollback

---

Cargo.toml

This should help fix the size of compiled library.

Remove debug info for release builds

---

automerge-c-v2/Cargo.toml

In the future we should rename it or find another way around this.

Don't document automerge-c-v2 due to name clash

---

.travis.yml

If we want to self-host them then we should also check that we don't break building them.

Add building docs to CI

---

automerge-backend-wasm/src/lib.rs
automerge-backend/Cargo.toml
automerge-backend/src/change.rs
automerge-backend/src/sync.rs
automerge-c-v2/src/lib.rs
automerge-c/src/lib.rs
perf/src/main.rs

Currently all changes get compressed when converting from a protocol change to a backend change.
This compression is actually quite costly time-wise and some use cases might not want to always compress changes, rather they can tolerate the slightly larger size. (For instance I am happy to save the changes in larger format and just save an entire document when space gets too much).
This PR makes the change to have compression as an opt-in. Users just call `compress` on a change they have and then the `raw_bytes` call will return the compressed version.
I've added compression to changes to be synced as this is a use case I can imagine it may be more acceptable to run compression on. Also note that this is likely to be a lot fewer changes getting compressed.
Some other question points:

Reduce deflate compression on the hot path

---

automerge-backend/src/expanded_op.rs
automerge-frontend/src/lib.rs
automerge-frontend/tests/test_apply_patch.rs
automerge-protocol/Cargo.toml
automerge-protocol/src/lib.rs
automerge-protocol/src/utility_impls/actor_id.rs
automerge-protocol/tests/serde_round_trip.rs
automerge-protocol/tests/serde_round_trip_proptest.rs
automerge/tests/frontend_backend_roundtrip.rs
automerge/tests/save_load.rs

Most of the time users will not be using their own identifiers and so
use random uuids. These can fit nicely on the stack for a speedup.
TinyVec allows us to capture this mostly stack, sometimes heap
behaviour.

Use tinyvec for actor id

---

automerge-frontend/src/lib.rs
automerge-frontend/src/mutation.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/optimistic.rs

This change allows us to store only one copy of the `StateTree` while avoiding having to `clone` it for safety. This is doable by adding rollbacks and an optimistic state wrapper.
Fixes #226

Optimistic state tree

---

automerge-backend-wasm/src/lib.rs
automerge-backend/src/backend.rs
automerge-c-v2/src/lib.rs
automerge-c/src/lib.rs
automerge-frontend/tests/test_backend_concurrency.rs
automerge/benches/crdt_benchmarks.rs
automerge/examples/cards.rs

The `_mut` variant is used so that people can `compress` after.

Make apply_local_change return ref to change

---

automerge-frontend/Cargo.toml
automerge-frontend/src/state_tree/diffable_sequence.rs
automerge-frontend/src/state_tree/mod.rs
automerge-frontend/src/state_tree/sequence_tree.rs
perf/src/main.rs

Taking some inspiration from [joseph's blog article](https://josephg.com/blog/crdts-go-brrr/) as well as seeing very poor performance in the flamegraphs from `im_rc::Vector` I decided to work on a simple btree-like implementation for sequences.
This doesn't do anything fancy like RLE encoding sequences of opids but does give us a very nice speed up and changes the bottleneck.
On my machine the main branch (`3c786b26`) runs the automerge trace (as implemented in the `perf` binary, roughly) in about 45 seconds, while this branch (at time of writing) runs in about 2 seconds.

Sequence tree

---

automerge-backend/src/backend.rs
automerge-backend/src/change.rs
automerge-backend/src/columnar.rs
automerge-backend/src/decoding.rs
automerge-backend/src/expanded_op.rs
automerge-backend/tests/bad_hashes.rs
automerge-cli/Cargo.toml
automerge-cli/src/examine.rs
automerge-cli/src/main.rs
automerge-protocol/src/lib.rs

The javascript implementation of automerge sorts actor IDs
lexicographically when encoding changes. We were sorting actor IDs in
the order the appear in the change we're encoding. This meant that the
index that we assigned to operations in the encoded change was different
to that which the javascript implementation assigns, resulting in
mismatched head errors as the hashes we created did not match the
javascript implementation.
This change fixes the issue by introducing a `HexActoId` type which we
use to sort actor IDs lexicographically. We make a pass over the
operations in the change before encoding to collect the actor IDs and
sort them. This means we no longer need to pass a mutable `Vec<ActorId>`
to the various encode functions, which cleans things up a little.
Fixes #240

Correctly sort actor IDs when encoding changes

---

automerge/Cargo.toml
automerge/src/lib.rs
automerge/tests/helpers/mod.rs
automerge/tests/test.rs

This commit adds a bunch of testing infrastructure as well as most of the tests from the `legacy_tests.js` file in the js codebase that seem applicable to this codebase.
There are a few small changes in `automerge/src/lib.rs` which should be checked for correctness. The majority of the work here though is in adding some macros to make it maintain these tests going forward.

Add some rust tests

---

.github/workflows/ci.yaml
automerge-js/package.json
scripts/ci/js_tests
scripts/ci/run

We add a script for running the js tests in `scripts/ci/js_tests`. This
script can also be run locally. We move the `automerge-js` package to
below the `automerge-wasm` crate as it is specifically testing the wasm
interface. We also add an action to the github actions workflow for CI
to run the js tests.

Run the js tests in CI

---

automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge/src/automerge.rs
automerge/src/visualisation.rs
flake.nix

The docs for set mention the return of an opid only when the document changes, which I would have expected a scalarvalue set to do. This adds the caveat that it is also required to create a new object in the document.
I think the docs on this could be clearer, maybe also mentioning that setting an object overwrites the old one (if it existed) thus returning an opid.

Add test and doc update for setting scalarvalues

---

automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge/src/automerge.rs
automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/visualisation.rs
flake.nix

Getting the length of a `Map` object doesn't seem to work.
At some point we'll also want to add a test for a case where an object gets changed from a list to an object and vice-versa to check we get the length of each respective one in history correctly.

Add length tests to props tests

---

automerge-js/test/legacy_tests.js
automerge-wasm/src/lib.rs
automerge-wasm/test/test.js
automerge/src/automerge.rs
automerge/src/columnar.rs
automerge/src/op_set.rs
automerge/tests/test.rs

Found a pretty surprising bug.  Lamport compare was being resolved in reverse order and so was conflict resolution... canceling each other out in all of the available tests.  Fixed both and added tests that would have caught this.  Going to make a PR to add these tests to automerge mainline as well.

Lamport compare was backward on Actor's and so was value resolution

---

automerge-wasm/test/test.ts

```
1) Automerge
basics
should handle merging text conflicts then saving & loading:
Error: there was a decoding problem
at /Users/okdistribute/dev/upwelling/api/automerge-rs/automerge-wasm/dev/index.js:1560:15
at logError (/Users/okdistribute/dev/upwelling/api/automerge-rs/automerge-wasm/dev/index.js:427:18)
at module.exports.__wbg_new_55259b13834a484c (/Users/okdistribute/dev/upwelling/api/automerge-rs/automerge-wasm/dev/index.js:1559:65)
at js_sys::Error::new::hbdf90002c6b69763 (wasm://wasm/01c8115e:0:4645140)
at automerge_wasm::interop::to_js_err::h69077334a2afb4da (wasm://wasm/01c8115e:0:3258952)
at core::ops::function::FnOnce::call_once::h4d2ed61124df3442 (wasm://wasm/01c8115e:0:4487290)
at core::result::Result<T,E>::map_err::h95c6f87840744bc3 (wasm://wasm/01c8115e:0:2945210)
at …
```

Add failing test for decoding a conflicted merge

---

automerge/src/automerge.rs
automerge/src/change.rs
automerge/src/columnar.rs

On my machine this takes the save benchmark (saving the edit-trace) from 132ms to 74ms, a rough 44% saving.

Optimise saving documents

---

automerge-wasm/src/lib.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/types.rs
automerge/tests/helpers/mod.rs
automerge/tests/test.rs

This helps to clean up the Rust API where getting the actor required `&mut self`.

Always have an actor on the document

---

automerge/src/automerge.rs
automerge/src/indexed_cache.rs
automerge/src/transaction/inner.rs

This fixes the case where a new actor would start to make a change (with a transaction) and then roll it back.
Previously it would leave the actor in the actors cache, meaning that they get written into the document (but not read again).
This handles undoing the changes on rollback properly.

Fix rolling back a transaction with a new actor

---

automerge/src/automerge.rs

This test shows that we can still access an object using its ID, even though it is no longer accessible in the document tree (using the paths). I assume that this is useful for cases such as conflicts but I wonder if there might be a way to make it more footgun-like? 
I'm ok with being able to look at old objects for historical reasons but I think trying to modify them should be an error.
As for how to detect that the object is not in the current document I'm not sure, maybe keep a running set of all the object ids in the document which we can alter as changes are made, or add a modifiable bool to each object?

Add test for overwriting a map and getting value from old one

---

.github/workflows/docs.yaml
automerge-backend-wasm/src/lib.rs

Before we release to crates.io and whilst we are developing changes it is useful to be able to visit the built docs. This PR adds the github action to build and push them to the `gh-pages` branch.
@orionz this would need the github pages to be setup under settings, I think you have access to do that if you'd be able to, just needs something like this 
An example is available [on my branch](http://jeffas.io/automerge-rs/automerge/)

Add docs workflow for gh-pages

---

automerge-cli/src/export.rs
automerge-cli/src/import.rs
automerge-cli/src/merge.rs
automerge-wasm/src/lib.rs
automerge/examples/quickstart.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/change.rs
automerge/src/encoding.rs
automerge/tests/test.rs
edit-trace/benches/main.rs

Save writes to a vec which is infallible and so the API should reflect that.

Make save infallible

---

automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge/src/encoding.rs
automerge/src/sync.rs
automerge/src/sync/bloom.rs
automerge/src/sync/state.rs

Bloom filter didn't need to consume itself when encoding. Writes are also infallible on a vec so no need for a result.

Clean up sync api

---

automerge/src/automerge.rs
automerge/src/types.rs

Default can be a footgun and confuse users, it was used internally but
that now uses the `from` impls. Also, opidat wasn't used and doesn't
seem to need to be public.

Cleanup actor id api

---

automerge-cli/src/import.rs
automerge-js/src/proxies.js
automerge-wasm/src/lib.rs
automerge/examples/quickstart.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/transaction/inner.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/transactable.rs
automerge/src/types.rs
automerge/src/value.rs
automerge/tests/test.rs
edit-trace/benches/main.rs
edit-trace/src/main.rs

This introduces a separation between the creation of objects and scalars in the API. This makes it safer to use the object id that gets returned when creating an object, as it will always be returned, and nothing will be returned for using a scalar.

Separate scalars and objects in transaction API

---

.github/workflows/ci.yaml
automerge-c/CMakeLists.txt
automerge-c/src/CMakeLists.txt
automerge-c/src/lib.rs
automerge-c/test/CMakeLists.txt
automerge-c/test/main.c

@orionz, I've added support for writing unit tests for the experimental C API with [CMocka](https://cmocka.org/).
I've ported the C API's original test cases from `automerge.c` to CMocka-based unit test cases in `test/main.c` and reconfigured CMake builds to validate themselves with it now.
I've left the potential removal of the original test cases in `automerge.c` file up to you.

Enable unit testing of the C API

---

automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge-wasm/src/sync.rs
automerge/examples/quickstart.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/lib.rs
automerge/src/sync.rs
automerge/src/sync/state.rs
automerge/src/transaction.rs
automerge/src/transaction/commit.rs
automerge/src/transaction/inner.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/result.rs
automerge/src/types.rs

- Commit now returns just a single hash rather than a vec. Since the
change we create from committing has all of the heads as deps there
can only be one hash/head after committing.
- Apply changes now takes a Vec rather than a slice. This avoids having
to clone them inside.
- transact_with now passes the result of the closure to the commit
options function
- Remove patch struct
- Change receive_sync_message to return a () instead of the
`Option<Patch>`
- Change `Transaction*` structs to just `*` and use the transaction
module
- Make CommitOptions fields public
- Move sync structs to module rather than being globally public

Misc API changes

---

automerge-wasm/index.d.ts
automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge-wasm/test/test.ts
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/error.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/transactable.rs

New api features of the wasm api.  Paths can be used instead of objid's. Also a materialize call has been added that recursively constructs a json object from a given path/objid.

add paths/materialize to api

---

automerge/src/autocommit.rs
automerge/src/automerge.rs

It doesn't do checks or raise errors so shouldn't really be exposed.

Stop exposing apply_change

---

automerge/src/automerge.rs
automerge/src/change.rs
automerge/src/columnar.rs
automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/transaction/inner.rs
automerge/src/types.rs
automerge/src/visualisation.rs

The `Op`s live in an `OpTree` which is one per object. The object id is already stored with the tree so we don't need to keep it in the Op too as it takes up space.
The `change` field was never actually read so seemed redundant.

Remove obj and change from Op

---

automerge-cli/src/examine.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/change.rs
automerge/src/columnar.rs
automerge/src/decoding.rs
automerge/src/encoding.rs
automerge/src/legacy/mod.rs
automerge/src/transaction/inner.rs

Doing some light fuzz testing revealed that during load we can get to a case where start_op is 0 but it shouldn't actually be possible. This change pushes that into the type system.

Make start_op be nonzero to prevent bad loads

---

automerge/src/automerge.rs
automerge/src/query/nth.rs
automerge/src/query/nth_at.rs
automerge/src/types.rs

This copies the test from https://github.com/automerge/automerge-rs/issues/311 into Rust and fixes the bug causing it. (Closes #311)
From some debugging it seems that (at least one of) the problems are around the `last_elem` variable not getting set in the query. The insert operation (which would set the `last_elem`) is in the first child node but gets skipped over so that in the second child node we are missing this state.
This is fixed by getting the elemid directly from the first op captured during the query when we want the key. This works as inserts are followed by non-inserts and non-inserts have an `elemid()` of the insert operation they overwrite.

Fix nth query's last_elem

---

automerge-cli/src/import.rs
automerge-js/src/counter.js
automerge-js/src/proxies.js
automerge-wasm/index.d.ts
automerge-wasm/src/lib.rs
automerge-wasm/test/test.ts
automerge/examples/quickstart.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/change.rs
automerge/src/columnar.rs
automerge/src/legacy/mod.rs
automerge/src/legacy/serde_impls/op.rs
automerge/src/legacy/serde_impls/op_type.rs
automerge/src/op_tree.rs
automerge/src/query.rs
automerge/src/transaction/inner.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/transactable.rs
automerge/src/types.rs
automerge/src/value.rs
automerge/src/visualisation.rs
automerge/tests/test.rs
edit-trace/automerge-wasm.js
edit-trace/benches/main.rs
edit-trace/src/main.rs

Rename `del` and `inc` to `delete` and `increment`.
I've also changed them in js/wasm but if that causes a conflict with js internals then we can revert the delete one.

Rename `del` and `inc` to `delete` and `increment`

---

automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge-wasm/src/value.rs
automerge/src/automerge.rs
automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/query.rs
automerge/src/query/insert.rs
automerge/src/query/keys_at.rs
automerge/src/query/len.rs
automerge/src/query/len_at.rs
automerge/src/query/list_vals.rs
automerge/src/query/list_vals_at.rs
automerge/src/query/nth.rs
automerge/src/query/nth_at.rs
automerge/src/query/opid.rs
automerge/src/query/prop.rs
automerge/src/query/prop_at.rs
automerge/src/query/seek_op.rs
automerge/src/query/seek_op_with_patch.rs
automerge/src/transaction/inner.rs
automerge/src/types.rs
automerge/src/value.rs
automerge/tests/helpers/mod.rs

Lots of the queries were cloning operations that they were going to return. This allows them to keep just the reference to the op that exists in the tree.
Additionally, rather than returning owned values of scalars that live in the ops we should just return a reference to them to make calls to `value` cheaper, and future iteration methods.

Have queries be able to return references to scalars

---

automerge/examples/watch.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/query.rs
automerge/src/query/elem_id_pos.rs
automerge/src/query/opid.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/transactable.rs
automerge/src/types.rs
automerge/src/visualisation.rs

In a scenario where we want to detect what key in the document has changed we can iterate through the ops in changes as they are applied, however these contain an obscure object id. This functionality helps the user by adding a method of going back up the tree from a found object to build the path to the original object.
There are currently some awkward bits that I'm not sure how we want to address such as the operation having an ObjectId whereas we need an ObjId for the document so we have to convert it to string first then import it.

Add `parent_object` and `path_to_object` functions

---

automerge-cli/src/import.rs
automerge-wasm/Cargo.toml
automerge-wasm/src/interop.rs
automerge/Cargo.toml
automerge/src/automerge.rs
automerge/src/transaction/transactable.rs
automerge/src/value.rs

Currently, we do an automatic split of strings into grapheme clusters on some calls but users can still insert normal strings into text. Since grapheme clusters and the algorithm behind splitting them is able to change with different revisions of the unicode spec I think we should leave this to users, as they require.
When we need to split things (`splice_text` and from js) we can just use the chars that make up the rust string, these are unicode scalars.

Remove grapheme splitting internally

---

automerge-js/package.json
automerge-js/src/index.js
automerge-js/src/proxies.js
automerge-wasm/README.md
automerge-wasm/index.d.ts
automerge-wasm/node-index.js
automerge-wasm/package.json
automerge-wasm/src/interop.rs
automerge-wasm/src/lib.rs
automerge-wasm/test/readme.ts
automerge-wasm/test/test.ts
automerge-wasm/tsconfig.json
automerge-wasm/web-index.js
automerge/Cargo.toml
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/error.rs
examples/cra/package.json
examples/cra/src/App.tsx

This is mostly a readme and packaging improvements for automerge-wasm.  There was some API cleanup as well.  Most notably the inclusion of a `fork_at()` method to allow a document to be forked at a point in time.

Wasm readme

---

automerge/src/automerge.rs
automerge/tests/test.rs

If a change got out of order queued multiple times it could be applied multiple times and corrupt internal state.  Added a test to expose the problem and a fix to fix it.  Code to prevent the problem at queue push time instead of pop time could be more memory efficient but as this is an unusual edge case I figured the simple fix would be good enough for now.

duplicate changes in the queue could corrupt internal state

---

automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/op_tree/iter.rs

The opset iterator was using `OpTreeInternal::get(index)` to fetch each
successive element of the OpSet. This is pretty slow. We make this much
faster by implementing an iterator which is aware of the internal
structure of the OpTree.
This speeds up the save benchmark by about 10%.
Signed-off-by: Alex Good <alex@memoryandthought.me>

Make the OpSet iterator faster

---

automerge/Cargo.toml
automerge/benches/map.rs
automerge/benches/range.rs
automerge/src/op_tree.rs
automerge/src/query.rs
automerge/src/query/elem_id_pos.rs
automerge/src/query/insert.rs
automerge/src/query/nth.rs
automerge/src/query/prop.rs
automerge/src/query/seek_op_with_patch.rs

Results from critcmp using the new benchmarks:
```
group                       main                                    opt-prop
-----                       ----                                    --------
decreasing put 1000         1.00  1267.9±80.15µs        ? ?/sec     1.13  1438.7±39.22µs        ? ?/sec
decreasing put 10000        1.00     16.0±1.14ms        ? ?/sec     1.24     19.9±1.24ms        ? ?/sec
increasing put 1000         1.00  1460.2±103.95µs        ? ?/sec    1.20  1750.3±16.75µs        ? ?/sec
increasing put 10000        1.00     19.6±1.08ms        ? ?/sec     1.28     25.1±1.18ms        ? ?/sec
repeated increment 1000     9.17     11.7±1.14ms        ? ?/sec     1.00  1277.1±14.38µs        ? ?/sec
repeated increment 10000    98.99 1708.5±55.31ms        ? ?/sec     1.00 …
```

Optimise prop query

---

automerge-c/CMakeLists.txt
automerge-c/cbindgen.toml
automerge-c/examples/CMakeLists.txt
automerge-c/examples/README.md
automerge-c/examples/quickstart.c
automerge-c/src/CMakeLists.txt
automerge-c/src/byte_span.rs
automerge-c/src/change_hashes.rs
automerge-c/src/changes.rs
automerge-c/src/doc.rs
automerge-c/src/lib.rs
automerge-c/src/result.rs
automerge-c/src/utils.rs
automerge-c/test/amdoc_property_tests.c
automerge-c/test/amlistput_tests.c
automerge-c/test/ammapput_tests.c
automerge-c/test/group_state.c
automerge-c/test/macro_utils.c

@orionz and @alexjg, this PR adds my port of `quickstart.rs` to the C API.
As with Rust's quickstart example, the instructions for building and running it are in the `automerge-c/examples/README.md` file.

Add a port of Rust's quickstart to the C API

---

automerge-c/examples/quickstart.c
automerge-c/test/macro_utils.h

@orionz, `examples/quickstart.c` should be reporting any error returned through an `AMresult` struct now.

Improve error reporting in C quickstart example.

---

.github/workflows/ci.yaml
automerge/src/op_tree/iter.rs

The previous implementation of nth was incorrect, it returned the nth
element of the optree but it did not modify the internal state of the
iterator such that future calls to `next()` were after the nth element.
This commit fixes that.
Signed-off-by: Alex Good <alex@memoryandthought.me>

Implement OpTreeIter::nth correctly

---

automerge/benches/map.rs
automerge/src/query/seek_op.rs
automerge/src/query/seek_op_with_patch.rs

This applies similar optimisations as the `Prop` query uses to skip over repeated overwrites in maps.
This happens to speed up loading (though may be outcompeted by Alex's work) for documents containing these operations but also speeds up applying changes (and so things like syncing too).

Optimise seek op and seek op with patch

---

automerge-js/src/common.ts
automerge-js/src/types.ts

Fix the `any` lint issues in `common.ts` by using an `UnknownObject` type alias. This is the correct type of arbitrary POJO-like objects where you don't know or care about the value types.
Added `Dictionary<T>` for the more standard cases where you have a `string` key and arbitrary (but known!) value types.

Use an `UnknownObject` type alias

---

automerge-c/src/lib.rs
automerge-cli/src/examine.rs
automerge-wasm/src/lib.rs
automerge-wasm/test/test.ts
automerge/Cargo.toml
automerge/benches/map.rs
automerge/benches/sync.rs
automerge/examples/quickstart.rs
automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/automerge/tests.rs
automerge/src/change.rs
automerge/src/clock.rs
automerge/src/error.rs
automerge/src/sync.rs
automerge/tests/test.rs

In order to improve sync performance I've taken a look at the `generate_sync_message` functionality and it was quite largely spending time in getting the changes, this can be especially bad when we can't use the fast version...
This PR optimises the `get_changes` function by doing the following:
- Maintain a vector clock for each change (hash) to allow constant time calculation of the vector clock
- Use this new `clocks` state to speed up finding the clock at any given hash
- Change `get_changes` to use the clocks under the hood, converting the hashes first to a single clock and then building the resulting changes from that
- Precalculate the number of operations in a change and store it alongside, otherwise we have to individually count the operations every time
This does add overhead to …

Get changes opt

---

automerge/src/automerge.rs
automerge/src/clock.rs
automerge/src/sync.rs

Mainly changing `filter_changes` to use the `clock_at` mechanism rather than doing graph traversals every time.

Some more sync optimisations

---

automerge-c/cbindgen.toml
automerge-c/examples/quickstart.c
automerge-c/src/byte_span.rs
automerge-c/src/change.rs
automerge-c/src/change_hashes.rs
automerge-c/src/changes.rs
automerge-c/src/doc.rs
automerge-c/src/doc/list.rs
automerge-c/src/doc/map.rs
automerge-c/src/result.rs
automerge-c/src/sync/haves.rs
automerge-c/src/sync/message.rs
automerge-c/src/sync/state.rs
automerge-c/test/amdoc_property_tests.c
automerge-c/test/amlistput_tests.c
automerge-c/test/ammapput_tests.c
automerge-c/test/group_state.c
automerge-c/test/group_state.h
automerge-c/test/macro_utils.h
automerge-c/test/sync_tests.c

@orionz, I've simplified the management of memory allocated by C API calls by reducing the `AMfree()`, `AMresultFree()` and `AMsyncStateFree()` functions to a single `AMfree()` function and making all functions that allocate memory return an `AMresult*`.

Simplify management of memory allocated by C API calls

---

automerge-c/examples/quickstart.c
automerge-c/src/CMakeLists.txt
automerge-c/src/change_hashes.rs
automerge-c/src/changes.rs
automerge-c/src/result.rs
automerge-c/src/sync/haves.rs
automerge-c/test/amdoc_property_tests.c
automerge-c/test/amlistput_tests.c
automerge-c/test/ammapput_tests.c
automerge-c/test/group_state.c
automerge-c/test/sync_tests.c

@orionz, I've made the following changes to the C API:
* Removed the artificial `index` argument from `AMresultValue()`.
* Added `AMchangeHashesReversed()`, `AMchangesReversed()` and `AMsyncHavesReversed()` to enable the creation of reverse iterators.
* Changed the interpretation of the `n` argument in `AM{changeHashes,changes,syncHaves}Advance()`, `AM{changeHashes,changes,syncHaves}Next()` and `AM{changeHashes,changes,syncHaves}Prev()` to apply their `n` arguments relatively instead of absolutely i.e. `AMchangesNext(&changes, 1)` advances `changes` one position regardless of whether its current direction is forward or reverse.
*  Obfuscated the members within the `AMchangeHashes`,  `AMchanges` and `AMsyncHaves` structs for safety and to permit their structures to change independently of …

Remove artificial iteration from the C API

---

automerge/src/value.rs

I'm assuming this was a mistake. I think the right way to serialize a Counter is to return its current value, not its start value.

Serialize Counter with it's current value instead of start value

---

automerge-c/src/CMakeLists.txt
automerge-c/src/actor_id.rs
automerge-c/src/change.rs
automerge-c/src/doc.rs
automerge-c/src/doc/utils.rs
automerge-c/src/lib.rs
automerge-c/src/result.rs
automerge-c/test/CMakeLists.txt
automerge-c/test/actor_id_tests.c
automerge-c/test/doc_tests.c
automerge-c/test/main.c
automerge-c/test/str_utils.c
automerge-c/test/str_utils.h
automerge-c/test/sync_tests.c
automerge/src/error.rs
automerge/src/lib.rs

@orionz, I've exposed the `automerge::ActorId` struct to C so that the logic to convert from a hexadecimal string to bytes and _vice versa_ wouldn't be repeated for multiple structs and so that a client application/library can synthesize a conforming actor identifier without guesswork.
@lightsprint09, this PR removes `AMgetActorHex()`, `AMsetActorHex()` and updates `AMgetActor()`, `AMsetActor()` and `AMchangeActorId()`.

Add `AMactorId` to the C API

---

automerge-c/examples/quickstart.c
automerge-c/src/CMakeLists.txt
automerge-c/src/actor_id.rs
automerge-c/src/byte_span.rs
automerge-c/src/change.rs
automerge-c/src/change_hashes.rs
automerge-c/src/changes.rs
automerge-c/src/doc.rs
automerge-c/src/doc/list.rs
automerge-c/src/doc/map.rs
automerge-c/src/doc/utils.rs
automerge-c/src/lib.rs
automerge-c/src/result.rs
automerge-c/src/strings.rs
automerge-c/src/sync/haves.rs
automerge-c/src/sync/message.rs
automerge-c/src/sync/state.rs
automerge-c/test/actor_id_tests.c
automerge-c/test/doc_tests.c
automerge-c/test/list_tests.c
automerge-c/test/map_tests.c
automerge/src/lib.rs

@orionz, I've added the `AMchangeHashesInit()`, `AMkeys()`, `AMspliceText()`, and `AMtext()` functions as well as the `AMstrings` struct to the C API.
@lightsprint09, I've removed `AMobjSizeAt()` from the C API because it wasn't symmetric with `automerge::AutoCommit::length_at()` and because I've added a `heads` argument to `AMobjSize()` which makes it symmetric with `automerge::AutoCommit::length_at()` when `heads != NULL`. I've also replaced some pointer arguments with `const` pointer arguments where possible.
BTW, it should be easier to compare the C quickstart example to the Rust one now that I've sublimated its memory management and, IMHO, its current form is also a more realistic example of a C program that uses Automerge.

Add AMkeys() to the C API

---

.github/workflows/docs.yaml
scripts/ci/cmake-docs

The test `CMakeLists.txt` brings in cmocka but we don't actually need to
build the tests to get the docs. This just makes the cmake docs script
tell cmake not to build docs.
Fixes #398

Don't build tests for docs

---

automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/automerge/tests.rs
automerge/src/error.rs
automerge/src/parents.rs
automerge/src/transaction/manual_transaction.rs
automerge/src/transaction/transactable.rs

There is easy confusion when calling parents with the id of a scalar,
wanting it to get the parent object first but that is not implemented.
To get the parent object of a scalar id would mean searching every
object for the OpId which may get too expensive when lots of objects are
around, this may be reconsidered later but the result would still be
useful to indicate when the id doesn't exist in the document vs has no
parents.
Fixes #388

Change parents to return result if objid is not an object

---

automerge/src/columnar.rs

Fixes https://github.com/automerge/automerge-rs/issues/394
Let me know if there is a more elegant approach than sorting after push, maybe using something like a BinaryHeap instead of Vec for the succ list.
Optree before fix (note the ordering of successors on line 5):
Optree after fix:

Make Op::add_succ sort succ vector after adding

---

automerge/Cargo.toml

Came up as a warning in a dry-run publish.
I've taken the current 'About' text from https://github.com/automerge/automerge.

publish: Add description to automerge crate

---

automerge/src/automerge.rs
automerge/src/columnar.rs
automerge/src/op_set.rs
automerge/src/op_tree.rs
automerge/src/op_tree/iter.rs
automerge/src/query.rs
automerge/src/transaction/inner.rs
automerge/src/types.rs
automerge/src/types/opids.rs

I was thinking a bit more about #401 and I've decided that actually we probably should maintain the op ID ordering invariant in the OpSet. My reasoning is that sorting op IDs when encoding forces us to allocate for every op in every change which has a succ when we commit a transaction and I worry about this affecting performance. This PR introduces an `OpIds` type which enforces the sorting invariant.

Add OpIds to enforce ordering of Op::succ and Op::pred

---

deny.toml

`unicode-idents` distributes some data tables from unicode.org which
require an additional license. This doesn't affect our licensing because
we don't distribute the data files - just the generated code. Explicitly
allow the Unicode-DFS-2016 license for unicode-idents.

Add license for unicode-idents

---

automerge-wasm/index.d.ts

I'm not sure if there are some configurations under which this works,
but I get
index.d.ts:2:21 - error TS1005: ';' expected.
2 export default from "automerge-types"
~~~~~~~~~~~~~~~~~
both in my project that depends on `automerge-wasm` and when I run `tsc`
in this repo.
It seems like `export default from` is still a Stage 1 proposal, so I
wouldn't expect it to be supported by TS, although I couldn't really
find hard evidence one way or the other. It does seem like this syntax
should be exactly equivalent based on the proposal doc though.

Fix TypeScript syntax error in `automerge-wasm` definitions

---

automerge-c/CMakeLists.txt
automerge-c/src/CMakeLists.txt
automerge-c/src/result.rs

> I've made a few changes to `automerge-c` to accomodate a new `ScalarValue::Unknown` variant. ... I've also not made any attempt to run the tests for automerge-c with a storage-v2 feature flag enabled.
@alexjg, this patch enables you to do that by appending `-DFEATURE_FLAG_STORAGE_V2=ON` to the CMake invocation.
The C API's unit test suite still passes when the "storage-v2" feature is enabled.

Patch C API changes for "storage-v2"

---

automerge-c/src/actor_id.rs
automerge-c/src/byte_span.rs
automerge-c/src/change.rs
automerge-c/src/change_hashes.rs
automerge-c/src/changes.rs
automerge-c/src/doc/list/items.rs
automerge-c/src/doc/map/items.rs
automerge-c/src/obj.rs
automerge-c/src/obj/items.rs
automerge-c/src/result.rs
automerge-c/src/strs.rs
automerge-c/src/sync/have.rs
automerge-c/src/sync/haves.rs
automerge-c/src/sync/state.rs
automerge/src/columnar/column_range/value.rs
automerge/src/error.rs
automerge/src/legacy/mod.rs

The latest clippy (90.1.65 for me) added a lint which checks for types
that implement `PartialEq` and could implement `Eq`
(`derive_partial_eq_without_eq`). Add a `derive(Eq)` in a bunch of
places to satisfy this lint.

Add #[derive(Eq)] to satisfy clippy

---

automerge/src/autoserde.rs

This type claims to implement `Deserialize` but actually implements `Serialize`.

Correct documentation for AutoSerde

---

automerge/src/autocommit.rs
automerge/src/automerge.rs
automerge/src/op_set.rs

Occasionally one needs to debug problems in a document with a large number of objects. In this case it is unhelpful to print a graphviz of the whole opset because there are too many objects. Add a `Option<Vec<ObjId>>` argument to `OpSet::visualise` to filter the objects which are visualised.

OpSet::visualise: add argument to filter by obj ID

---

automerge/src/storage/load/reconstruct_document.rs
automerge/tests/test.rs

The logic for reconstructing changes from the compressed document format records operations which set a key in an object so that it can later reconstruct delete operations from the successor list of the document format operations. The logic to do this was only recording set operations and not `make*` operations. This meant that delete operations targeting `make*` operations could not be loaded correctly.
Correctly record `make*` operations for later use in constructing delete operations.

Correctly load documents with deleted objects

---

automerge/src/query/prop.rs
automerge/tests/test.rs

The logic in `query::Prop` works by first doing a binary search in the OpTree for the node where the key we are looking for starts, and then proceeding from this point forwards skipping over nodes which contain only invisible ops. This logic was incorrect if the start index returned by the binary search was in the last child of the optree and the last child only contains invisible ops. In this case the index returned by the query would be greater than the length of the optree.
Clamp the index returned by the query to the total length of the opset.
Fixes #400

query::Prop: don't scan past end of OpTree

---

crates/automerge-wasm/src/interop.rs
crates/automerge-wasm/test/apply.ts
wrappers/javascript/src/index.ts
wrappers/javascript/test/basic_test.ts

Fixes #433. `getObjectId` was previously throwing an error if passed something which was not an object. In the process of fixing this I simplified the logic of `getObjectId` by modifying automerge-wasm to not set the OBJECT_ID hidden property on objects which are not maps, lists, or text - it was previously setting this property on anything which was a JS object, including `Date` and `Uint8Array`.

javascript: Make getObjectId tolerate non object arguments

---

automerge-c/src/lib.rs

I know this branch may not be actively maintained, but hoping to merge in a fix for a bug I found which prevented any documents from being loaded and the tests to fail. I'm using the [automerge-swift](https://github.com/automerge/automerge-swift) frontend which is currently built against an even older commit (cf2a5125a198653b83490b2c996e4f6982f98e57) from this repository. I'm working on at least updating it to this branch, which seems to be (at least close to) the latest point before the C frontend was completely rewritten.
Anyways, I bisected the issue to 1c61986d3 and this PR reverts the change that commit made to this function. The vector was being created with the correct capacity, but its length was not explicitly set, resulting in the caller getting a seemingly-empty vector.
Without …

Fixed bug with length not being set in C frontend of automerge-1.0

---

.github/workflows/ci.yaml
README.md
crates/automerge-wasm/.gitignore
crates/automerge-wasm/README.md
crates/automerge-wasm/package.json
crates/automerge-wasm/src/lib.rs
crates/automerge-wasm/test/readme.ts
crates/automerge-wasm/test/test.ts
wrappers/javascript/src/index.ts

Moved from `wasm-pack` to `wasm-bindgen-cli`. 
Updated wasm README and tests. 
Found a bug in `--weak-refs` when exporting top level functions that take ownership of arguments.  I changed the behavior of `exportSyncState()` and `encodeSyncState()` to not consume the object and updated `automerge-js` to free them manually.  
Using the `-Oz` flag for `wasm-opt`.  It seems to work pretty well but there are dozens of other flags we might want to look into.
The build process now makes files with different names - I updated `package.json` to point to the new names instead of adding file renaming to the build process.

Implement weak refs

---

javascript/examples/vite/README.md
javascript/examples/vite/vite.config.js
javascript/src/index.ts
javascript/test/basic_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/interop.rs
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/src/observer.rs

Enhancing the JavaScript wrapper to respect the `{ freeze: true }` flag recursively and behave properly on `load()` and `clone()`.

make freeze work recursively

---

javascript/examples/create-react-app/package.json
javascript/examples/vite/package.json
javascript/examples/webpack/package.json
javascript/package.json
rust/automerge-wasm/package.json
rust/automerge-wasm/src/observer.rs
rust/automerge-wasm/test/test.ts

One of the blutack documents was making 1700 patches on load - now it makes 2.  Was able to consolidate all of the inserts and deletes into a single patch.

consolidate inserts and deletes more aggressively into a single splice

---

javascript/src/index.ts
javascript/test/basic_test.ts

The logic for `clone` which was updated to support cloning a viewed document inadverantly left the heads of the cloned document state in place, which meant that cloned documents could not be `change`d. Set state.heads to undefined when cloning to allow changing them.

Allow changing a cloned document

---

rust/automerge-wasm/Cargo.toml
rust/automerge/Cargo.toml

This PR updates the rust uuid dependency to the latest version `1.2.1`. [According to the docs](https://docs.rs/uuid/1.2.1/uuid/index.html#webassembly) WebAssembly is now enabled through the `js` feature rather than `wasm-bindgen`.
All rust crates seem to compile just fine and passes all tests (using `--workspace --all-features`) without any further changes, but maybe someone with a bit more knowledge should try it as well (also maybe for the js side?).

Update rust uuid dependency to v1.2.1

---

rust/Cargo.toml
rust/automerge-wasm/package.json

We lost about 30% performance when moving from opt level 3 to 'z'.  Reverting it.

revert compiler flags to max opt

---

rust/Cargo.toml
rust/automerge-test/Cargo.toml
rust/automerge-test/README.md
rust/automerge-test/src/lib.rs
rust/automerge/Cargo.toml
rust/automerge/tests/test.rs

The `assert_doc` and `assert_obj` macros in automerge/tests::helpers are useful for writing tests for any application working with automerge documents. Typically however, you only want these utilities in tests so rather than packaging them in the main `automerge` crate move them to a new crate (in the spirit of `tokio_test`)

Move automerge/tests::helpers to crate automerge-test

---

rust/automerge-c/src/doc.rs
rust/automerge-c/src/doc/list.rs
rust/automerge-c/src/doc/map.rs
rust/automerge-c/src/obj.rs
rust/automerge-c/src/result.rs
rust/automerge-c/test/list_tests.c
rust/automerge-c/test/macro_utils.c
rust/automerge-c/test/map_tests.c
rust/automerge-c/test/ported_wasm/basic_tests.c

@orionz, @alexjg and @ConradIrwin, I've done the following to ease writing language bindings based upon the C API:
* Exposed `autocommit::AutoCommit::object_type()` as `AMobjObjType()`.
* Replaced the phrase "Lamport timestamp" with "epoch timestamp" within the documentation.

Add AMobjObjType()

---

rust/automerge-wasm/src/interop.rs
rust/automerge/src/sync.rs
rust/automerge/src/sync/state.rs

The API of Automerge::generate_sync_message requires that the user keep track of in flight messages themselves if they want to avoid sending duplicate messages. To avoid this add a flag to `automerge::sync::State` to track if there are any in flight messages and return `None` from `generate_sync_message` if there are.

Dont send duplicate sync messages

---

javascript/src/index.ts
javascript/test/basic_test.ts
rust/automerge-c/src/doc.rs
rust/automerge-c/src/result.rs
rust/automerge-c/test/ported_wasm/basic_tests.c
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.ts
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/tests.rs
rust/automerge/src/op_observer.rs
rust/automerge/src/transaction.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/src/transaction/observation.rs
rust/automerge/src/transaction/result.rs

Transactions with no ops in them are generally undesirable. They take up space in the change log but do nothing else. They are not useless though, it may occasionally be necessary to create an empty change in order to list all the current heads of the document as dependents of the empty change.
The current API makes no distinction between empty changes and non-empty changes. If the user calls `Transaction::commit` a change is created regardless of whether there are ops to commit. To provide a more useful API modify `commit` so that if there is a no-op transaction then no changes are created, but provide explicit methods to create an empty change via `Transaction::empty_change`, `Automerge::empty_change` and `Autocommit::empty_change`. Also make these APIs available in Javascript and C. …

Transaction empty

---

README.md
rust/automerge-c/README.md
scripts/ci/cmake-build

I've added a bunch of documentation on setting up the build environment (which was challenging to me as a rust newbie), and some more detailed documentation for automerge-c (to clarify expectations around concurrency, types, strings with null characters, etc.).

Improve docs for building automerge-c on a mac

---

rust/automerge-c/src/byte_span.rs
rust/automerge-c/src/doc/list.rs
rust/automerge-c/src/doc/map.rs
rust/automerge-c/test/list_tests.c
rust/automerge-c/test/map_tests.c
rust/automerge-c/test/ported_wasm/basic_tests.c

After #457  there was an inconsistency between AMmapPutString (which took an AMbyteSpan) and AMmapPutBytes (which took a pointer + length).
Either is fine, but we should do the same in both places. I chose this path to make it clear that the value passed in was an automerge value, and to be symmetric with AMvalue.bytes when you do an AMmapGet().
I did not update other APIs (like load) that take a pointer + length, as that is idiomatic usage for C, and these functions are not operating on byte values stored in automerge.
/cc @jkankiewicz @orionz

Use AMbyteSpan for AM{list,map}PutBytes

---

rust/automerge/src/automerge.rs
rust/automerge/src/change.rs
rust/automerge/src/clock.rs
rust/automerge/src/columnar/column_range/key.rs
rust/automerge/src/columnar/column_range/obj_id.rs
rust/automerge/src/columnar/column_range/opid.rs
rust/automerge/src/columnar/column_range/opid_list.rs
rust/automerge/src/columnar/encoding/properties.rs
rust/automerge/src/op_set.rs
rust/automerge/src/op_tree.rs
rust/automerge/src/op_tree/iter.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/src/types.rs
rust/automerge/src/types/opids.rs

Making OpId a little smaller speeds up the edit-trace by 10% on rust and wasm.  This does limit us to 4 billion ops per document which should be fine.  Should we ever be able to approach numbers like that its a simple fix to change it back to u64 as the u32 is hidden as a private.

change opid to (u32,u32) 

---

README.md

Slack invite link updated to the one used on the website, as the current one returns "This link is no longer active".

Update README.md (Update Slack invite link)

---

rust/automerge-c/Cargo.toml
rust/automerge-cli/Cargo.toml
rust/automerge-cli/src/color_json.rs
rust/automerge-cli/src/examine.rs
rust/automerge-cli/src/export.rs
rust/automerge-cli/src/main.rs
rust/automerge/Cargo.toml
rust/deny.toml
rust/edit-trace/Cargo.toml

Automerge CLI depends transitively (via and old version of `clap` and via `colored_json` on `atty` and `ansi_term`. These crates are both marked as unmaintained and this generates irritating `cargo deny` messages. To avoid this, implement colored JSON ourselves using the `termcolor` crate - colored JSON is pretty mechanical. Also update criterion and cbindgen dependencies and ignore the criterion tree in deny.toml as we only ever use it in benchmarks.
All that's left now is a warning about atty in cbindgen, we'll just have to wait for cbindgen to fix that, it's a build time dependency anyway so it's not really an issue.

automerge-cli: remove a bunch of bad dependencies

---

rust/automerge-cli/src/color_json.rs
rust/automerge-cli/src/examine.rs
rust/automerge-cli/src/examine_sync.rs
rust/automerge-cli/src/export.rs
rust/automerge-cli/src/main.rs
rust/automerge/src/automerge.rs
rust/automerge/src/storage.rs
rust/automerge/src/storage/load.rs
rust/automerge/src/storage/load/reconstruct_document.rs

This is useful when debugging corrupted documents. While we're here I also
* Fixed the broken colored JSON implementation I pushed a few days ago
* Added an `examine-sync` command for dumping the contents of sync messages

Allow loading CLI changes without verifying heads

---

rust/automerge-wasm/index.d.ts

The `IncPatch` type currently has its action as 'put', but the patch provided following a counter increment contains an 'inc' action.

Update action name on `IncPatch` type

---

.github/workflows/release.yaml

This is a first step to automating `automerge` releases for both npm and deno. Changing the version number in the wasm `package.json` file will trigger a build and then push code to both npm and deno.land.

Add workflow to generate a `wasm` release when pushing new version

---

javascript/.prettierignore
javascript/scripts/denoify-replacer.mjs
scripts/ci/cmake-build
scripts/ci/deno_tests
scripts/ci/fmt_js
scripts/ci/js_tests
scripts/ci/lint
scripts/ci/rust-docs
scripts/ci/wasm_tests

Some of the scripts in scripts/ci were not reliable detecting the path they were operating in. Additionally the deno_tests script was not correctly picking up the ROOT_MODULE environment variable. Add more robust path handling and fix the deno_tests script.

Various CI script fixes

---

rust/automerge/src/exid.rs
rust/automerge/src/lib.rs

The `ExId` structure has some internal details which make lookups for object IDs which were produced by the document doing the looking up faster. These internal details are quite specific to the implementation so we don't want to expose them as a public API. On the other hand, we need to be able to serialize `ExId`s so that FFI clients can hold on to them without referencing memory which is owned by the document (ahem, looking at you Java).
Introduce `ExId::to_bytes` and `TryFrom<&[u8]> ExId` implementing a canonical serialization which includes a version tag, giveing us compatibility options if we decide to change the implementation.

automerge-rs: Add `ExId::to_bytes`

---

rust/automerge/src/op_set.rs
rust/automerge/src/parents.rs
rust/automerge/src/query.rs
rust/automerge/src/query/elem_id_pos.rs

Problem: the `OpSet::export_key` method uses `query::ElemIdPos` to determine the index of sequence elements when exporting a key. This query returned `None` for invisible elements. The `Parents` iterator which is used to generate paths to objects in patches in `automerge-wasm` used `export_key`. The end result is that applying a remote change which deletes an object in a sequence would panic as it tries to generate a path for an invisible object.
Solution: modify `query::ElemIdPos` to include invisible objects. This does mean that the path generated will refer to the previous visible object in the sequence as it's index, but this is probably fine as for an invisible object the path shouldn't be used anyway.
While we're here also change the return value of `OpSet::export_key` to an …

fix: don't panic when generating parents for hidden objects

---

rust/automerge/src/columnar/encoding/leb128.rs
rust/automerge/tests/test.rs

Before this change numbits_i64() was incorrect for every value of the
form 0 - 2^x. This only manifested in a visible error if x%7 == 6 (so
for -64, -8192, etc.) at which point `lebsize` would return a value one
too large, causing a panic in commit().

Fix and simplify lebsize calculations

---

rust/automerge/src/value.rs

This makes it easier to use `SmolStr`s directly and pass them into automerge.

Add From<SmolStr> for ScalarValue::Str

---

javascript/src/stable.ts
javascript/src/unstable.ts
rust/automerge-wasm/index.d.ts

Added new `InsertPatch` type, which now applies to inserts on `Text` and `List`/`Sequence` elements.
Added new `SpliceTextPatch` type which is produced when text is added to a `TextV2` string element.
Removed `SplicePatch` type, which no longer exists.

Update patch types

---

rust/automerge/src/storage/parse.rs
rust/automerge/src/storage/parse/leb128.rs

Before this change i64 decoding did not work for negative numbers (not a
real problem because it is only used for the timestamp of a change),
and both u64 and i64 would allow overlong LEB encodings.
I have another PR that needs some polish that begins to use this for handling
value column decoding, but this should stand alone.

More robust leb128 parsing

---

javascript/test/legacy_tests.ts
rust/automerge/Cargo.toml
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/current_state.rs
rust/automerge/src/automerge/tests.rs
rust/automerge/src/lib.rs
rust/automerge/src/op_set.rs
rust/automerge/src/op_set/load.rs
rust/automerge/src/storage/chunk.rs
rust/automerge/src/sync.rs
rust/automerge/src/transaction/inner.rs
rust/deny.toml

Currently when we load a document or receive a sync message into an empty document we call the `OpObserver` for every single operation in the entire document. For documents with a deep history this can be very slow and it also requires us to buffer ops rather than streaming them directly into the `OpSet`, which slows construction of the `OpSet`.
This PR changes things so that for a new or empty document we first construct the `OpSet`, and then traverse the ops in the `OpSet` notifying the `OpObserver` of only the visible ops. This is much, much, faster. This is addressing the same problem as #507 but guarantees that observers (and thus the patch callback in JS) will be notified of all visible changes.
The change this PR introduces only works when loading into an empty document. In …

Minimal diff on load

---

rust/automerge-wasm/Cargo.toml
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/src/observer.rs
rust/automerge-wasm/src/sequence_tree.rs
rust/automerge/src/lib.rs

The `SequenceTree` is only ever used in `automerge_wasm` so move it there.

Move automerge::SequenceTree to automerge_wasm::SequenceTree

---

javascript/test/basic_test.ts
rust/automerge-wasm/test/test.ts
rust/automerge/src/op_tree/node.rs
rust/automerge/src/query/prop.rs
rust/automerge/src/query/seek_op.rs
rust/automerge/src/query/seek_op_with_patch.rs
rust/automerge/src/sync.rs

Found a bug in the op_tree query skip code.  Moved all the logic in into op_tree/node.rs and made it much simpler.  Added a test.

rework how skip works to push the logic into node

---

.github/workflows/ci.yaml
rust/automerge/src/storage/parse.rs

This clippy warning was causing issues when running `./scripts/ci/run`; one option would be to rename the getter, or to switch up the naming of the fields, but I figured suppressing the clippy warning would be reasonable.
```
error: getter function appears to return the wrong field
--> automerge/src/storage/parse.rs:311:5
|
311 | /     pub(crate) fn bytes(&self) -> &'a [u8] {
312 | |         self.original
| |         ------------- help: consider using: `self.bytes`
313 | |     }
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#misnamed_getters
= note: `-D clippy::misnamed-getters` implied by `-D warnings`
error: could not compile `automerge` due to previous error
```

Suppress clippy warning in parse.rs + bump toolchain

---

.github/workflows/ci.yaml
README.md
rust/Cargo.toml
rust/automerge-c/CMakeLists.txt
rust/automerge-c/test/byte_span_tests.c

Generate significantly smaller automerge-c builds
This cuts the size of libautomerge_core.a from 25Mb to 1.6Mb on macOS
and 53Mb to 2.7Mb on Linux.
As a side-effect of setting codegen-units = 1 for all release builds the
optimized wasm files are also 100kb smaller.

smaller automerge c

---

rust/automerge-cli/src/main.rs

Behavior without this patch is `thread 'main' panicked at 'Found non-required positional argument with a lower index than a required positional argument: "input_file" index Some(1)', /home/issac/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.11/src/builder/debug_asserts.rs:647:17`
```
automerge/rust/automerge-cli on  main [!] is 📦 v0.1.0 via 🦀 v1.68.0 via ❄️  impure (nix-shell-env) 
❯ git stash
Saved working directory and index state WIP on main: a7f751fa Merge pull request #551 from wjt/patch-1
automerge/rust/automerge-cli on  main [$] is 📦 v0.1.0 via 🦀 v1.68.0 via ❄️  impure (nix-shell-env) 
❯ cargo run -- examine /tmp/database.mismatcheheads.20230322 --skip-verifying-heads
warning: /home/issac/src/automerge/rust/edit-trace/Cargo.toml: unused manifest key: bench.0.debug …
```

Decorate skip verify flag on examine command.

---

rust/automerge/src/lib.rs
rust/automerge/src/op_tree.rs
rust/automerge/src/op_tree/node.rs
rust/automerge/src/query/insert.rs
rust/automerge/src/query/nth.rs
rust/automerge/src/query/seek_op_with_patch.rs
rust/automerge/src/sequence_tree.rs
rust/automerge/tests/test.rs

This PR fixes a bug in the `Nth` query which led to it not counting the visible element in the parent after skipping a child node.

fix: `Nth` query sometimes miscounting

---

javascript/src/unstable.ts
javascript/test/marks.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/marks.ts
rust/automerge/Cargo.toml
rust/automerge/src/autocommit.rs
rust/automerge/src/marks.rs
rust/automerge/src/op_observer.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/src/transaction/transactable.rs
rust/automerge/tests/test.rs

This lets users have more control over how marks are removed.
Along the way add a bit of documentation to the marks feature
Fixes #577

Allow custom expand on unmark

---

rust/automerge/src/storage/change/change_op_columns.rs

They now match the ids in doc chunks
Fixes #575

Renumber marks columns in change chunks

---

rust/automerge/Cargo.toml

Due to a series of unfortunate events involving feature resoution and the tracing-subscriber and regex crates, the tracing-subscriber integration in our tests was crashing. This is detailed here: https://github.com/tokio-rs/tracing/issues/2565
For now we work around this by adding a dev dependency on regex which enables the required features. tracing-subscriber will be updated shortly and then we will need to get the updated tracing-subscriber into test-log and then we can relax.

Fix regex/tracing-subscriber dependency hell

---

javascript/test/basic_test.ts
rust/automerge/src/automerge.rs
rust/automerge/src/exid.rs

Found a bug where `doc.get[_all]()` would return results in the wrong order when a conflict existed.  This would lead to the wrong conflict being materialized on document load in the javascript client.

conflict ordering bug in `doc.get*()`

---

rust/automerge/Cargo.toml

Now that `tracing-subscriber` has been updated to use the correct feature flags for `regex` we can remove the workaround implemented in 17b29d43ba6f7ba8c4b96862c0fcc53a1d9b8cf1

Remove regex/tracing-subscriber build error workaround

---

rust/automerge/src/automerge.rs
rust/automerge/src/exid.rs

A bug was found in the ExId(ObjId) Cmp implementation.  I did not believe it was needed outside the project so I removed the need for it internally and removed the bad implementation.  Turns out someone wanted it.  I've restored it bug free.  My primary concern here is that instead of a proper unit test I added an `assert_eq!()` macro to `get_all[_at]()` and to show that all results do not change order when sorted.  Looking for feedback if this is sufficient to test the code.

restore ability to sort ObjId

---

javascript/src/stable.ts
javascript/src/types.ts
javascript/test/legacy_tests.ts
javascript/test/marks.ts
javascript/test/patches.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.ts

This fixes #593. Passing the pointer to the current document into the callback from the webassmebly side is basically never going to be safe because we end up with multiple borrows of the doc. Even if we were to not pass the doc pointer into the callback, the user could do something unsafe by calling another method on a reference to the document retained elsewhere. Instead, we run the callback in JS, so we don't have to worry about re-entrant borrows of the document.

wasm/js: Run patchCallback in JS, not in webassembly

---

rust/automerge/src/storage/save/document.rs

Switching to precalculating change indices in a HashMap rather than a BTreeMaps cuts about 20% off of Automerge::save for large histories.

Make Automerge::save slightly faster for large histories

---

.gitignore
javascript/e2e/verdaccio.yaml
javascript/package.json
rust/automerge-wasm/.gitignore
rust/automerge-wasm/Cargo.toml
rust/automerge-wasm/examples/cloudflare/.gitignore
rust/automerge-wasm/examples/cloudflare/package.json
rust/automerge-wasm/examples/cloudflare/src/index.js
rust/automerge-wasm/examples/cloudflare/wrangler.toml
rust/automerge-wasm/package.json
rust/automerge-wasm/src/export-web-wasm.js

Cloudflare Workers uses a slightly different way of importing and using `.wasm` modules ([details](https://blog.cloudflare.com/webassembly-on-cloudflare-workers/)) This adds a new build that leverages `wasm-bindgen`'s `web` target and stitches it together with a entry file.

Add support for cloudflare workers

---

javascript/src/stable.ts
javascript/src/unstable.ts
javascript/test/patches.ts

Frequently it is useful to get a set of patches which take you from one set of heads in a document to another. Add automerge.diff to achieve this.

js: Add automerge.diff

---

rust/automerge/src/op_tree.rs
rust/automerge/src/query.rs
rust/automerge/src/query/prop.rs

The old code was optimized to be fast if there were many props with few updates but not few props with many updates.  This is optimized for both.

Fixes performance regression on maps (#601)

---

javascript/src/proxies.ts
javascript/test/proxies.ts

`List.splice` seems to not function entirely as per the javascript spec. This is a failing test for now, which I will update with a fix shortly.

Fix for `List.splice`

---

javascript/src/types.ts
javascript/src/unstable.ts
javascript/src/unstable_types.ts
javascript/test/basic_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/cursor.ts

We added a cursor api to the rust a while back - exposing it to wasm and js.  Currently only the unstable `Automerge::splice()` can take the cursor as an index, however the  `Automerge::getCursorPosition()` call can be used anywhere else.  Added this because of #603

add getCursor/getCursorPosition allow use in js::splice()

---

javascript/src/proxies.ts
javascript/src/text.ts
javascript/test/text_v1.ts

In the next major release of automerge, we'll expose the new text
API; but in the meantime, let's fix this footgun in the existing
implementation.
I decided against adding yet another API (.insertTextAt) because
it seems likely that it'd be deprecated in the next release anyway.

Handle splitting string into code points (Fixes #602)

---

javascript/src/unstable.ts
javascript/test/basic_test.ts
rust/automerge-c/src/doc.rs
rust/automerge-wasm/src/lib.rs
rust/automerge/src/autocommit.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/src/transaction/transactable.rs
rust/edit-trace/benches/main.rs
rust/edit-trace/src/main.rs

This allows cursors to be used for common text editing operations
without having to recalculate indices.
Add some documentation and tests while I'm at it.
I think this (coupled with the new API using javascript-native string indices) fully addresses the idea in #603.

Allow negative `del` for splice (Fixes #603)

---

javascript/src/unstable.ts
javascript/test/marks.ts
rust/automerge/src/transaction/inner.rs

This makes the indices passed to mark() match those passed to splice().

Unicode aware offsets for mark/unmark

---

javascript/package.json
javascript/src/unstable.ts
javascript/test/basic_test.ts
javascript/test/change_at.ts
javascript/test/patches.ts
javascript/test/text_v1.ts

We weren't running ts-mocha with the --typecheck option, which meant that the tests had accumulated some type errors. Run typechecking for tests in CI so the tests stay clean.

js: Run typechecking for tests in CI

---

javascript/src/stable.ts
javascript/src/types.ts
javascript/src/unstable.ts
javascript/test/basic_test.ts

There was an unnecessary call to `view()` that would call an expensive `materialize()` that was not needed.  Removing for performance reasons.

JS: don't materialize on view

---

javascript/src/stable.ts
javascript/test/change_at.ts

Context: The `changeAt` function "isolates" the document at some heads and then executes a change callback on the isolated document. This allows the user to run a change callback as if it were operating on the document as at the given heads, rather than whatever the "current" state is. Once the change callback is complete `changeAt` calls `automerge_wasm::Automerge::integrate` to move the document back to the current heads of the document (those that were active before the call to `changeAt`).
Problem: The logic for calling `integrate` - which is in `_change` - when the callback was complete did not handle the case where the callback made no changes at all. This left the document pointing at the isolated heads even after the `changeAt` call was complete.
Solution: Modify the `_change` …

js: integrate isolated doc in changeAt on empty change

---

rust/automerge/src/autocommit.rs

Context: `Automerge::diff` allows you to generate patches from any set of heads to any other set of heads in the document. In the general case this requires constructing a set of clocks for each set of heads to determine which ops should be visible in the set of patches. However, `Automerge::diff` also has some logic to check for cases where we can skip building clocks in order to generate the patches faster.
Problem: The logic to skip building clocks was incorrectly failing to skip generating clocks in the case when the `before` heads were empty and the `after` heads were the heads of the document (i.e. when generating a patch for the whole current state of the document).
Solution: Set the `PatchLog::heads` clock to `None` in the case of a full history patch to skip clock generation. …

Dont build clocks when making whole-document patches

---

javascript/src/low_level.ts
javascript/src/proxies.ts
javascript/src/stable.ts
javascript/src/types.ts
javascript/src/unstable.ts
javascript/src/unstable_types.ts

This will be of specific use to `automerge-repo`.
This also tidies up a few unused imports

Add `PatchInfo` and `PatchSource` types to exports

---

javascript/src/counter.ts

This adds dummy `increment` and `decrement` methods back in to the `Counter` class.
Method parameters are prefixed with `_` to avoid eslint errors. We could also add `/* eslint-disable @typescript-eslint/no-unused-vars */` to the file if that is preferred.
It can also be added above each method signature, but I am not sure how that effects doc comments being detected properly.
Closes #662

Added dummy counter methods

---

javascript/src/proxies.ts
javascript/test/text_v1.ts

textv1: Allow multiple codepoint characters when initializing Text

---

javascript/src/stable.ts
javascript/test/basic_test.ts
javascript/test/change_at.ts

`changeAt` is useful because it allows the user to choose when they synchronize state with the document by saving the heads of the last sync point and then applying changes since that last sync point using `changeAt`. This only goes one way however, to go in the other direction the user needs to be able to obtain the diff from the now applied changes to the state of the document including any other concurrent changes. To enable this modify `changeAt` to return a `{newDoc: Doc<T>, newHeads: Heads | null}` instead of just `Doc<T>`. The returned `newHeads` is the hash of the transaction created by the change callback and can be used as the `before` argument to `diff` to obtain a diff from the result of the changeAt call to the state of the document including concurrent changes.

js: Return heads of new changes from changeAt

---

rust/automerge/src/autocommit.rs
rust/automerge/src/automerge/current_state.rs
rust/automerge/src/automerge/diff.rs
rust/automerge/src/iter/list_range.rs
rust/automerge/src/iter/top_ops.rs
rust/automerge/src/marks.rs
rust/automerge/src/op_tree.rs
rust/automerge/src/patches/patch_builder.rs
rust/automerge/src/patches/patch_log.rs
rust/automerge/src/query/insert.rs
rust/automerge/src/query/opid.rs
rust/automerge/src/transaction/inner.rs

We use an `Rc` internally when generating patches. This inadvertantly made `AutoCommit` `!Send`. Swap `Rc` for `Arc` to make `AutoCommit` `Send` again, add a test to make sure this remains the case.
Fixes #681

rust: Make AutoCommit Send again

---

javascript/src/text.ts
javascript/test/text_v1.ts

I noticed that `slice()` on text doesn't actually return the value, so the return is always `undefined`.
This PR adds a fix and a test case.

text/v1: return value in slice()

---

rust/automerge-c/CMakeLists.txt

automerge-c: Add an explicit dependency on ntdll for WIN32

---

javascript/src/next.ts
javascript/src/stable.ts
javascript/test/basic_test.ts
rust/automerge-c/Cargo.toml
rust/automerge-wasm/.editorconfig
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.ts
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/lib.rs
rust/automerge/src/storage.rs
rust/automerge/src/storage/load.rs
rust/automerge/tests/test.rs

The behaviour of `Automerge::load` and all derived APIs has so far been to throw an error if, having finished loading, we find that there are changes which have missing dependencies. This is because it seemed like it would be surprising if you call `load` on a saved file and the document was empty. There are situations however where you know that there may be missing dependencies. Add a flag to `load` to indicate that missing depencies are okay to accomodate this.

javascript: Allow loading a document with missing changes

---

javascript/src/next.ts
javascript/src/stable.ts
javascript/test/basic_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.ts
rust/automerge/src/autocommit.rs

In the rust codebase we have a method `Automerge::save_after` which saves the changes since a given set of heads. Expose this as `saveSince` in javascript so that users can implement things like `saveIncremental` in user space.

javascript: Expose saveSince

---

javascript/config/cjs.json

Problem: In the last set of changes we migrated the main tsconfig for @automerge/automerge to ouput ES modules. This tsconfig is included in the tsconfigs used to produce the commonjs output which means that the modules in `dist/cjs` were in fact ES modules and consequently commonjs applications barfed when importing.
Solution: Set `"module": "commonjs"` in `javascript/config/cjs.json` so that we continue to output commonjs modules for commonjs dependents.
Fixes #718

Use correct module format for commonjs

---

rust/automerge/src/op_tree.rs
rust/automerge/src/query/seek_mark.rs
rust/automerge/tests/test_mark_patches.rs

Problem: Applying a change which adds a mark to the last character in a text object would not generate a patch for the change in question. The reason this occurs is to do with the fact that  marks are implemented as two consecutive operations, a `MarkBegin` op and a `MarkEnd` op. The logic to determine whether to generate a patch is implemented as a `TreeQuery` (specifically, as `SeekMark`). The `TreeQuery` gets called for every element in the text sequence and scans through looking for the last `MarkBegin` of the same type as the target `MarkEnd`, and then counts indices until the insertion index is encountered. This fails if the insertion index is at the end of the sequence because the `TreeQuery` never gets called.
Solution: Add a `SeekMark::finish` method which checks if the end mark …

Fix missing marks at end of text

---

javascript/src/proxies.ts
javascript/src/raw_string.ts

@orionz , @issackelly This PR adds a `toString()` method to the `RawString` class. This makes it easier to uniformly handle `string` and `RawString` in code, as you can simply call `toString()` on any value of either type and get a string representation of it.

add toString() method to RawString object

---

javascript/package.json
javascript/scripts/transpile-cjs.mjs

Problem: Previously, in 5f43505bc88d8789b9279c88505280559cb83443 I modified the typescript config to output commonjs modules for commonjs consumers. However, the module format being correct doesn't actually fix things because when loading the module the loader (well, node at least) notices that the package the cjs output is in has `"type": "module"` and so attempts to load the JS as ESM modules and chokes.
Solution: Output the js files in `dist/cjs` with a `*.cjs` suffix. This lets node know that these files are definitely absolutely commonJS modules and please load them as commonjs modules, thank you. Unfortunately `tsc` won't do this for us as it requires not just renaming the output files, but also rewriting the import paths in the transformed files to havea a `*.cjs` suffix and …

js: Transpile ESM to CommonJS

---

javascript/src/next.ts
javascript/src/stable.ts
javascript/test/stable_unstable_interop.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/current_state.rs
rust/automerge/src/lib.rs
rust/automerge/tests/convert_string_to_text.rs

Add functionality to convert strings to text on load
Problem: As people transition to the new `next` JavaScript API they need to handle old data which is using scalar strings instead of text sequences. The way this manifests is that data which was a `string` in the old API appears as a `RawString` when loaded using the new API. This means that people have to either write code which handles both `RawString` and `string`, or write code which converts the `RawString` to `string`.
Solution: Offer an option to automatically convert the old strings (which are `ScalarValue::Str` in Rust) to text sequences when loading the document. This is achieved by actually adding a change to the document setting all visible string values to text values with the same contents. This isn't a complete solution …

Convert strings to text on load

---

javascript/src/stable.ts
javascript/test/patches.ts

Problem: the typescript types for diff check that the arguments `before` and `after` are arrays of strings, but if the user ignores those types (or is using javascript) then we don't actually check at runtime that they are valid. These arrays get passed through to the wasm, which can explode messily.
Solution: throw a nice exception in `diff` so that at least the user can find out where they went wrong

js: check arguments to diff are actually arrays

---

rust/automerge-c/examples/quickstart.c
rust/automerge-c/test/cmocka_utils.c
rust/automerge-c/test/ported_wasm/basic_tests.c

* Changed `abort_cb()` to always free the  memory allocated for its `data` argument.
* Changed `cmocka_cb()` to always free the  memory allocated for its `data` argument.
* Prevented MSVC warning C4090 in `test_should_be_able_to_fetch_changes_by_hash()`.

automerge-c: Fix issue #738

---

rust/automerge-c/README.md

The `putResult` variable is accidentally used both in the debug code for put and for get. In the second case `getResult` should probably have been used instead.

Fix accidental re-use of putResult in README.md example

---

javascript/src/internal_state.ts
javascript/src/stable.ts

I don't love this! But here it is, a band-aid for a performance problem.
What this does is every time you call progressDocument, that patch is also cached on the new document. (LRU=1) When you make a new call to progressDocument, the patch is replaced. 
To benefit from this, we check in diff if there's a saved patch with exactly those heads and if so, we return them!
This allows you to call diff() with the same arguments a few times in a row and memoize the result.
Well, first I'm not a huge fan of shoving stuff into the InternalState object but... it seems relatively harmless.
The tests all pass but it could probably use a couple of extra tests to stress it. I did test that if I messed up the various inputs that it would fail in expected ways but there's not a test that targets this …

Cache the last patch on the document's InternalState

---

javascript/src/next.ts
javascript/src/next_types.ts
javascript/src/types.ts
javascript/test/marks.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/marks.mts
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/diff.rs
rust/automerge/src/marks.rs
rust/automerge/src/query/insert.rs
rust/automerge/src/query/nth.rs
rust/automerge/src/read.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/src/transaction/manual_transaction.rs

added a `marksAt()` to the js and wasm interface.  The rust version im calling `get_marks()` because `marks_at()` was already taken - but since im going to be removing all the `_at()` methods in the branches PR I chose to take the name I want where there wasn't already a conflict.
Also fixed the issue in issue  #646 where the last mark was not being reported properly in the patch generated by splices at the edge of an expanding mark.

adds marksAt() method and Fixes #646

---

rust/automerge-c/CMakeLists.txt
rust/automerge-c/cmake/Cargo.toml.in
rust/automerge-c/docs/CMakeLists.txt
rust/automerge-c/examples/CMakeLists.txt
rust/automerge-c/test/CMakeLists.txt

While developing a C++ library that depends upon automerge-c, I discovered that its CMake build system wasn't flexible enough and that the following features were required:
* Empower an external build tool to dictate the names of its constituent libraries.
* Enable its CMake project to be built as a subdirectory of a dependent CMake project.
* Incorporate the "automerge_core" (Rust bindings) library into the "automerge" (Rust bindings + utilities) library so that it could furnish all of the symbols.
:information_source: This PR includes the changes for #725 and #774.

automerge-c: Improve build flexibility

---

rust/automerge/Cargo.toml
rust/automerge/src/change_graph.rs
rust/automerge/src/clock.rs

`clock_at()` is scaling at O(n) and is becoming a problem with apps making a change per keystroke 
Changed Clock to use `im::HashMap` to make clones quick and memory usage shared between clocks.
Added a cache to ChangeGraph to cache evey 32nd clock.  When generating a clock walk backwards until hitting a cached clock and stop.
This should make clock_at() to be O(1)

Cache clocks for faster clock_at()

---

rust/automerge-c/test/CMakeLists.txt

@alexjg, this PR corrects the target name mismatch between PR #780 and PR #781.

automerge-c: Re-enable testing after merge of PR #781

---

rust/automerge-c/src/doc/mark.rs
rust/automerge-c/test/mark_tests.c

These changes prevent warning messages like the following when compiling with GCC:
```
In file included from .../automerge/rust/automerge-c/test/mark_tests.c:11:
.../automerge/rust/automerge-c/test/mark_tests.c: In function ‘test_AMmark_round_trip’:
.../automerge/rust/automerge-c/test/mark_tests.c:51:54: warning: passing argument 2 of ‘AMitemToMark’ from incompatible pointer type [-Wincompatible-pointer-types]
51 |     assert_true(AMitemToMark(AMitemsNext(&marks, 1), &mark));
|                                                      ^~~~~
|                                                      |
|                                                      AMmark **
In file included from .../automerge/rust/automerge-c/test/mark_tests.c:14:
.../automerge/rust/automerge-c/rust/automerge-c/build/include …
```

automerge-c: Prevent "incompatible pointer type" warnings in mark tests

---

rust/automerge-c/CMakeLists.txt
rust/automerge-c/src/doc/list.rs
rust/automerge-c/src/doc/map.rs
rust/automerge-c/src/result.rs
rust/automerge-c/test/list_tests.c
rust/automerge-c/test/map_tests.c

One goal of "C API 2" (PR #530) was for a value's corresponding index (e.g. string key within its parent map object or positive integer position within its parent list object) to be available regardless of how it was retrieved and not just when iterating over its parent object.
Unfortunately, "C API 2" only laid the groundwork for achieving that goal so this PR finally pushes it over the finish line with the following changes:
* Changed `AMlistGet()` to store the returned `AMitem` struct's index within it.
* Changed `AMlistPutObject()` to store the returned `AMitem` struct's index within it.
* Changed `AMmapGet()` to store the returned `AMitem` struct's index within it.
* Changed `AMmapPutObject()` to store the returned `AMitem` struct's index within it.
* Bumped the patch version from …

automerge-c: Always store its index in an `AMitem` struct

---

rust/automerge-c/Cargo.toml
rust/automerge-c/cmake/Cargo.toml.in
rust/automerge-test/Cargo.toml
rust/automerge/Cargo.toml

Bump this dependency to the latest version.  No breaking changes seem to affect the use of this dependency in `automerge`.

Upgrade `smol_str` to `0.2`

---

.github/workflows/advisory-cron.yaml

Ever since commit dd3c6d130 ("Move rust workspace into ./rust") this job seems to have been failing on not finding a `Cargo.toml` in the root.
This was fixed for the "main" CI on pushes and pull requests in commit e8309495c ("Update `cargo deny` to point at `rust` subdirectory"), but not for the scheduled cron job leading to unnecessary failures in (fork) repos.

Run cron advisories job on `rust` folder

---

javascript/src/proxies.ts
javascript/test/legacy_tests.ts
javascript/test/proxies.ts

Context: The change callback which is used to modify an automerge document is passed a proxy which looks like a POJO but intercepts mutating calls and converts them into operations on the underlying document.
Problem: When setting a key of one of the proxies in the change handler to `undefined` the proxy throws a RangeError. This is necessary because automerge doesn't support `undefined` - only `null`. However, the `RangeError` doesn't contain any information which allows the developer to figure out where they passed in an invalid value.
Solution: Include a JSON pointer to the path the developer attempted to insert the invalid value at so they can identify what part of their data they need to change.

javascript: Better errors when setting invalid values

---

javascript/test/sync_test.ts
rust/automerge-wasm/src/interop.rs
rust/automerge-wasm/test/test.mts
rust/automerge/src/sync.rs
rust/automerge/src/sync/state.rs

Context: The sync protocol maintains a sync state which is updated every time we send or receive a message. This sync state contains a field for the heads the other end has reported. This is useful for applications to understand what local changes the other hand has not yet acknowledged.
Problem: In some cases we never send a response to the first message in the sync protocol and so the other end never learns what our heads are. The reason this happens is that we have some optimisations in the protocol to not send a message if we can tell that the other end has all the same changes as us. One scenario where this happens is if you load a document you previously saved and then synchronise that document with a sync server which already has the document and there have been no new changes. …

Always send at least one sync message

---

rust/automerge-wasm/src/interop.rs
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/src/value.rs
rust/edit-trace/package.json

Optimize the code that generates and patches js objects from wasm.   Gives a 10x performance boost over the main branch on a problem document supplied by @pvh  (10246 ms vs 1061 ms)
Of the remaining 1000ms 
30% is spent creating the javascript object -  this is what this PR optimizes - not obvious how to make this faster
30% is spent loading the document - this will speed up with the faster load PR
15% is spent creating the rust patches 
25% if spent converting those patches into js objects.
I'm wondering if some system to make the patches lazily would be better since those patches are taking 40% of the load time and are not always used.  Something for future work

generate and patch js objects more efficiently

---

rust/automerge-wasm/Cargo.toml
rust/automerge-wasm/src/export_cache.rs
rust/automerge-wasm/src/interop.rs
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/src/value.rs
rust/automerge/src/automerge.rs
rust/automerge/src/iter/list_range.rs
rust/automerge/src/iter/map_range.rs
rust/automerge/src/iter/top_ops.rs
rust/automerge/src/op_set.rs
rust/automerge/src/storage/load/change_collector.rs

This is primarily code cleanup to replace a recursive algorithm with a non-recursive one.  In the course of writing this I found several low hanging fruit and was able to gleam a 20% performance improvement for the `large-scene` use case with 1M objects.   We also identified an opportunity to get another 25-50% speedup via using a WeakMap to store metadata.
Before
`Load :  8965 ms   Materialize :  6724 ms    -- ./larger-scene.amg`
After
`Load :  7856 ms   Materialize :  5050 ms    -- ./larger-scene.amg`

Optimize code to materialize js objects from wasm

---

rust/automerge/src/sync.rs
rust/automerge/src/sync/message_builder.rs
rust/automerge/src/sync/v1_compat_test/mod.rs

Problem: some older clients were throwing an error when parsing sync messages from sync protocol upgrades introduced in d6c67f41e626493bf83612dc58c1829842ebe195. The problem is that the new protocol was encoding changes using `crate::Change::bytes`, rather than `crate::Change::raw_bytes`. The former compresses the change if it larger than a certain threshold but the old sync protocol is not capable of handling compressed changes.
Solution: use `raw_bytes` rather than `bytes` to avoid compressing changes.

Fix a backwards incompatibility in the new sync messages

---

rust/automerge/Cargo.toml
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/cursor.rs
rust/automerge/src/lib.rs
rust/automerge/src/patches/patch_log.rs
rust/automerge/src/read.rs
rust/automerge/src/sync.rs
rust/automerge/src/sync/state.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/src/value.rs

Found some markdown that was either:
- Missing backticks;
- Had the ` `` ` around `[]` so that it wouldn't turn into a link but display as a single-item array;
- Missing `[]` so that it would not link to an item/function;
- Some invalid `Self::` references that should have pointed to another type (rustdoc points this out and it helps the user understand and click what the docs are referring to);
- Added `()` at the end of functions for readability (and forces `rustdoc` to ensure that the target item really is an `fn`).

rust: Improve some intradoc links

---

javascript/src/next.ts
javascript/test/text_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/update_text.mts
rust/automerge/Cargo.toml
rust/automerge/src/autocommit.rs
rust/automerge/src/lib.rs
rust/automerge/src/text_diff.rs
rust/automerge/src/text_diff/LICENSE
rust/automerge/src/text_diff/myers.rs
rust/automerge/src/text_diff/utils.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/src/transaction/transactable.rs
rust/automerge/tests/text.rs

Problem: updating text fields in an automerge documents requires using splice, which is intended for use when capturing individual input events as the user creates them. In some environments it is impossible to capture these events, leaving the developer to try and figure out a set of splice calls. This is reasonably fiddly work.
Solution: introduce Transactable::update_text (which is exposed in javascript as Automerge.updateText). This method performs a myers diff to calculate a minimal set of edits to make based on the new text which is passed to it.
The implementation is copied from the `similar` crate, which is licensed under the Apache license. This necessitates including the Apache 2 license alongside the cribbed code as well as attribution comments in the (2) files which were …

Introduce Automerge.updateText (rust: Transactable::update_text)

---

rust/automerge-wasm/package.json

This fixes an issue related to importing/resolving types when using Typescript `moduleResolution: Node16 | NodeNext | Bundler`
Before this change, you would get the following error when trying to import types directly from `@automerge/automerge-wasm`:
```
// Example import
import { Patch } from "@automerge/automerge-wasm";
// Error
Diagnostics:
typescript: Could not find a declaration file for module '@automerge/automerge-wasm'. 'node_modules/@automerge/automerge-wasm/nodejs/automerge_wasm.cjs' implicitly has an 'any' type.
There are types at 'node_modules/@automerge/automerge-wasm/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@automerge/automerge-wasm' library may need to update its package.json or typings. [7016]
```
After the change in …

Fix relative path for exports.types

---

rust/automerge-c/CMakeLists.txt
rust/automerge-c/cmake/Cargo.toml.in
rust/automerge-c/docs/CMakeLists.txt
rust/automerge-c/examples/CMakeLists.txt
rust/automerge-c/test/CMakeLists.txt

Upgrading the CMake project's requirement to CMake >= 3.25 enables the `block` statement and the `block` statement enables a dependent CMake project to add a copy of the automerge-c library's root project directory as a subdirectory without risking variable collisions.

automerge-c: Upgrade to CMake >= 3.25

---

rust/automerge/src/query/insert.rs
rust/automerge/src/query/list_state.rs
rust/automerge/src/query/nth.rs
rust/automerge/src/query/opid.rs

Problem: In 70438774f2f8a52a1346458a968249b3634696bc I fixed a bug where marks were not being correctly calculated when a clock was passed to the `nth` query. This was actually a special case of a more general problem where we were not taking account of clocks passed to various queries when processing marks.
Solution: Add an `Option<Clock>` argument to `MarkMap::process` and do the visibility check in `process` rather than in the caller.

Add a clock argument to MarkMap::process

---

README.md

The current one expired, I got this new one (which will supposedly never expire) from slack.

Update discord invite link in README

---

.github/workflows/advisory-cron.yaml
.github/workflows/ci.yaml
rust/automerge/src/op_set/op.rs
rust/automerge/src/sync.rs

It looks like cargo-deny stopped working after the [1.5.14 release](https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.5.14). I noticed the runs fail on [my previous PR](https://github.com/automerge/automerge/actions/runs/8125155370/job/22207538386?pr=862).
I found [a ticket noting such](https://github.com/EmbarkStudios/cargo-deny-action/issues/73), and this PR should resolve the issue for now, but it's also worth considering pinning the action to a specific version.
Additionally, this implements a few clippy suggestions that were causing the lint GitHub action to fail.

Ensure cargo-deny and lint actions pass

---

rust/automerge/src/automerge.rs
rust/automerge/tests/convert_string_to_text.rs

Fixes https://github.com/automerge/automerge/issues/872
When using `StringMigration::ConvertToText`, a transaction is made when loading the document. This isn't necessary and just causes ballooning of the document for no reason.
This PR corrects this issue by only committing the transaction if there are strings to convert.

Only commit conversion transaction when there are valid conversions

---

rust/automerge/src/automerge.rs
rust/automerge/src/indexed_cache.rs
rust/automerge/src/op_set/op.rs
rust/automerge/src/storage/save/document.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/tests/test.rs

Context: The logic to rollback a transaction removed the actor ID of the current actor if actor had no ops in the document. The purpose of this was to stop actors with no ops in the OpSet from being written to the document when calling `Automerge::save`. Also of note, actor IDs in the document are not references to `ActorId`s, but indexes into a cached array of `ActorId`s.
Problem: the logic to remove the actor ID contained a check that the actor ID being removed was the last actor in the cached array of actor IDs. This was not always true. For example, committing an empty transaction, then merging changes from another peer would mean that the final index in the cache was for a different actor ID to the current actor.
Solution: Instead of attempting to remove the actor ID on rollback, …

Fix a panic when rolling back a transaction

---

rust/automerge-cli/src/export.rs
rust/automerge/src/autoserde.rs

Problem: the JSON formatting which automerge-cli uses emitted text sequences as arrays of characters. This is counterintuitive as the JS implementation now uses javascript strings and it's also irritating to read.
Solution: switch to emitting text as a JSON string. Also clean up the implementation by using the `automerge::AutoSerde` implementation of `serde::Serialize` to serialize the doc to `serde_json` rather than the custom implementation in `automerge-cli`.

rust/cli: emit text as string in JSON

---

rust/automerge/src/automerge.rs
rust/automerge/src/automerge/diff.rs
rust/automerge/src/patches/patch_builder.rs
rust/automerge/src/patches/patch_log.rs
rust/automerge/src/read.rs

Problem: in documents with histories that create a large number of objects patch generation can become slow due to the cost of computing the path for each path. We don't store the path anywhere in the document, instead each OpTree stores the ID of op which created it; this in turn means that to compute the path to an object we recursively seek through the opset for each object in the path. In documents which have a large number of ops - and especially if these ops are split over many small objects - these seek operations can take a long time.
Solution: when we think we have more than a few paths to generate (this patch arbitrarily choosese 100 paths) first precompute all the visible paths in the document and then use this lookup table. To put this in concrete terms, I have a document …

precompute visible paths when generating patches

---

rust/automerge/src/indexed_cache.rs
rust/automerge/src/op_set/op.rs
rust/automerge/src/storage/save/document.rs
rust/automerge/tests/test.rs

Problem: in f10981 I modified the logic of `Automerge::save()` to do a scan over the ops in the document when determining which actors to save. This logic fails to account fo empty commits by actors who never make any ops.
Solution: rather than scanning the ops, scan the changes.

include actor IDs from missing changes in save

---

rust/automerge/src/iter/spans.rs
rust/automerge/src/marks.rs
rust/automerge/tests/text.rs

Problem: Automerge::spans could produce unpredictable results when there were zero length marks in a text sequence. The zero length marks would cause the surrounding text to be broken into two spans, even if the marks on the surrounding text had not changed.
Solution: only flush spans when we see text for the new marks.

fix: always merge spans with the same marks in Automerge::spans

---

rust/automerge/src/iter/spans.rs
rust/automerge/tests/text.rs

Problem: e6d60d32 fixed an error where empty marks split spans which had equal marks on either side. The fix introduced a bug where the character after a block marker and an empty mark was double counter.
Solution: don't double count the character.

fix: Automerge::Spans -> don't double count after block markers

---

rust/automerge/src/automerge.rs
rust/automerge/tests/test.rs

Problem: when a change produced large numbers of patches (more than 100) some patches could end up with incorrect indexes. The reason for this was that the optimization which kicks in at > 100 patches which precalculates the paths for every visible object in the document was using the wrong encoding for calculating the indexes in lists.
Solution: use the correct encoding.

fix: correct index calculations for large patch sets

---

rust/automerge/src/query/insert.rs
rust/automerge/tests/text.rs

Problem: in text which has a mark ending at the end of the text but which was set to not expand on insertions at the end, insertions were nevertheless still producting patches which contained the mark. The reason was that the logic in the insert query for processing the end-mark operations was only running when the next visible operation _after_ the mark operations was processed.
Solution: run the mark processing logic when we encounter the end mark operation.
While I was here I also added some exposition to the earlier test exposing a problem with marks which cross optree boundaries and generally cleaned that test up.

splice: fix no-expand marks at the end of text

---

javascript/test/patches.ts
rust/automerge/src/automerge/diff.rs
rust/automerge/src/patches/patch_log.rs
rust/automerge/tests/test.rs

Problem: when diffing "in reverse", i.e. where the start heads are topologically after the end heads in the change graph, the patches produced would not include objects which are "undeleted".
Solution: when traversing the OpSet if we encounter ops which make create an object and which were visible before the heads we are starting from, then mark the object as exposed so that the ExposeQueue will render the object to the patch log later.
fixes #708

Fix missing objects in reverse patches

---

javascript/test/error.ts
javascript/test/legacy_tests.ts
rust/automerge/src/error.rs
rust/automerge/src/transaction/inner.rs
rust/automerge/tests/test.rs

According to discussion over on #852, there really isn't a reason why keys can't be empty. 
This PR allows this by simply removing the check and error.
Resolves #852

Allow empty keys in maps

---

javascript/src/internal_state.ts
javascript/src/stable.ts
javascript/src/uuid.deno.ts
javascript/src/uuid.ts

When running `npm run lint`, a few errors appear:
```
$ npm run lint --fix
> @automerge/automerge@2.2.2 lint
> eslint src
automerge/javascript/src/internal_state.ts
11:20  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
automerge/javascript/src/stable.ts
113:3  error  Unnecessary semicolon  @typescript-eslint/no-extra-semi
127:3  error  Unnecessary semicolon  @typescript-eslint/no-extra-semi
automerge/javascript/src/uuid.deno.ts
11:31  error  Don't use `Function` as a type. The `Function` type accepts any function-like value.
It provides no type safety when calling the function, which can be a common source of bugs.
It also accepts things like class declarations, which will throw at runtime as they will not be called with `new`.
If you are expecting …
```

Fix lint errors

---

javascript/src/proxies.ts
javascript/test/proxies.ts

The global function [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) does not copy the prototype chain and because of it, objects resulting from this function fail the current check.
This PR resolves this issue by using a different check described in [this blog post](https://www.zhenghao.io/posts/js-data-type).
Resolves https://github.com/automerge/automerge/issues/915

Better check for plain objects

---

javascript/src/proxies.ts
javascript/test/proxies.ts

The test for a recursive document as a value was broken as a parameter `context` was omitted from the function arguments. This was not caught by TypeScript as `context` is a part of mocha in tests.
This PR corrects this issue and adds an appropriate tests to catch future issues like this.
Resolves #914

Correctly pass `context` parameter to `import_value`

---

javascript/src/proxies.ts
javascript/test/legacy_tests.ts
javascript/test/proxies.ts

Ran into this behavior today and was surprised by it.
```js
it("does not support undefined values", () => {
let doc = Automerge.init<any>()
assert.throws(() => {
doc = Automerge.change(doc, doc => {
doc.foo = undefined
})
}, "Unsupported type undefined")
})
```
After some head-scratching I realized that `undefined` is not a valid JSON value. 
The full error message you get is `Unsupported type undefined at path /a/b/c", which wasn't super helpful to me. 
This PR changes the error messages for this and similar situations so that they point the developer in the right direction.

More helpful error message when assigning `undefined` to a property

---

javascript/HACKING.md
javascript/scripts/build.mjs
javascript/src/low_level.ts
javascript/src/next_slim.ts
javascript/src/stable.ts
javascript/test/sync_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.mts
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/tests/test.rs

Problem: it's often useful for the application to be able to tell
whether a remote peer has all the changes we have, but currently that
requires understanding the internal state of the automerge::sync::State
struct.
Solution: Add a method to Automerge and AutoCommit that returns true if
the replica represented by the sync state has all the changes we have.

Has our changes

---

rust/automerge-c/CMakeLists.txt
rust/automerge-c/src/actor_id.rs
rust/automerge-c/src/byte_span.rs
rust/automerge-c/src/change.rs
rust/automerge-c/src/cursor.rs
rust/automerge-c/src/doc.rs
rust/automerge-c/src/doc/mark.rs
rust/automerge-c/src/index.rs
rust/automerge-c/src/item.rs
rust/automerge-c/src/items.rs
rust/automerge-c/src/lib.rs
rust/automerge-c/src/obj.rs
rust/automerge-c/src/result.rs
rust/automerge-c/src/sync/state.rs
rust/automerge-c/test/CMakeLists.txt
rust/automerge-c/test/actor_id_tests.c
rust/automerge-c/test/cursor_tests.c
rust/automerge-c/test/main.c
rust/automerge-c/test/ported_wasm/cursor_tests.c
rust/automerge-c/test/ported_wasm/suite.c
rust/automerge-c/test/ported_wasm/sync_tests.c
rust/automerge/src/cursor.rs

@alexjg, I've finally exposed the Cursor API to C programs.
In order to make the full unit test suite pass again, I also included the changes from PR #885 that I authored.
@heckj can either rebase PR #885 onto main after this PR is approved or he can open a new PR for his changes.

automerge-c: Expose Cursor API

---

javascript/src/next_slim.ts
javascript/src/stable.ts
javascript/test/basic_test.ts
rust/automerge-wasm/index.d.ts
rust/automerge-wasm/src/lib.rs
rust/automerge-wasm/test/test.mts
rust/automerge/src/autocommit.rs
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/diff.rs
rust/automerge/src/read.rs
rust/automerge/src/transaction/manual_transaction.rs
rust/automerge/tests/test.rs
rust/deny.toml

Problem: sometimes it is hard to know why performance is suffering for a given document. Often, the issue is that the document history is large, but it's not easy to examine this in a general manner.
Solution: Add a `Automerge.stats` function that returns a JSON object indicating the number of changes and the number of ops in the document.

Add Automerge.stats

---

rust/automerge-wasm/package.json

1. we don't care for a fallback path
2. this file is imported in the bundler entrypoint that shouldn't see the fallback path
3. vite and rspack (and maybe other?) bundlers see the `new URL(".wasm", import.meta.url)` output when the fallback path is there and include an extra .wasm in the assets. it's not actually any harm but it's ugly and makes people feel like they did something wrong
i've confirmed on my local machine that this stops the `new URL(".wasm", import.meta.url)` from being output, but i haven't been able to run the tests. it took me an hour just to get it to build and i dont have the emotional fortitude to tackle the tests, let's see what CI says

don't include a fallback path for the wasm

---

rust/automerge-c/Cargo.toml
rust/automerge-wasm/Cargo.toml
rust/automerge/Cargo.toml
rust/automerge/src/automerge.rs
rust/automerge/src/automerge/current_state.rs
rust/automerge/src/automerge/diff.rs
rust/deny.toml
rust/edit-trace/Cargo.toml
rust/edit-trace/benches/main.rs
rust/edit-trace/src/main.rs

Various updates to move to the latest version of `cargo-deny`:
* Update `cbindgen` and `itertools` to remove duplicate dependencies in our depenency tree
* Switch from depending on `json` to `jzon` in the `edit-trace` crate as `json` is no longer maintained
* Modify the deny.toml config to remove deprecated keys

Cargo deny updates

---

javascript/src/next_slim.ts
javascript/test/cursors.ts

Problem: The `getCursor(doc, path, number)` - which returns a stable identifier
for a given index into a text object - always resolved the index with
respect to the latest heads of the document. In particular, if you
passed the result of `Automerge.view` as the first argument to
`getCursor` and then attempted to get a cursor for an index which had
since been deleted then a `RangeError` was thrown.
Solution: Respect the heads of the document passed to `getCursor` when
resolving the index.

make getCursor work with Automerge.view

---

rust/automerge-c/CMakeLists.txt

This does the change suggested in #868.
I wanted to update automerge-go, but I can't build it because the current steps for automerge-go require macos.

automerge-c: remove options that don't work on mac

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
rust/rust-toolchain.toml

Problem: due to an intersection of changes in LLVM and wasm-bindgen described here[1], compiling with rustc1 1.82.0 breaks the WebPack webassembly integration. It looks like wasm-bindgen plan to push a fix for this (despite it not really being their responsibility) but that's not in yet.
Solution: pin the compiler to 1.81 until the wasm-bindgen fix is int.
[1]:  https://github.com/rustwasm/wasm-bindgen/issues/4211

rust: Pin to rustc 1.81

---

rust/automerge-wasm/Cargo.toml

Problem: The wasm-bindgen dependency of automerge-wasm has to be exactly the same as the version of the CLI used to build the JavaScript package. The CI environment is pinned to a specific version in the Github actions workflow but the version of wasm-bindgen in the Cargo.toml file is not.  This means that when a new version of wasm-bindgen is released, the build fails because cargo automatically pulls the latest version of wasm-bindgen which is different to the version used in the CI environment.
Solution: Pin the version of wasm-bindgen in the Cargo.toml to the same version as in CI.

automerge-wasm: Pin version of wasm-bindgen

---

README.md
rust/automerge-c/README.md
rust/automerge-c/cmake/enum-string-functions-gen.cmake
rust/automerge-c/cmake/file-regex-replace.cmake
rust/automerge-c/cmake/file-touch.cmake
rust/automerge-c/docs/CMakeLists.txt
rust/automerge-c/examples/CMakeLists.txt
rust/automerge-c/test/CMakeLists.txt

This PR fixes various documentation bugs related to building the reference documentation for the automerge-c library.
:eyes: @alexjg @msakrejda @orionz

[#980] Documentation on how to build automerge-c docs is broken

---

rust/automerge/src/text_diff.rs
rust/automerge/tests/text.rs
rust/deny.toml

`Transaction::update_text` implements a diff based method for modifying text in an automerge document. The method accepts a new string and performs a myers diff between the new string and the existing string in order to determine the changes that need to be made to the text.
Calling `update_text` from within a transaction that is based on non-current heads (such as within an `AutoCommit` on which you have called `AutoCommit::isolate`) would erroneously calculate the diff against the text from the latest heads, rather than the heads the transaction was based on. This commit fixes the issue by using the transaction heads to materialize the text to diff against.

Fix bug with `update_text` at old heads

---

rust/automerge/src/automerge.rs
rust/automerge/src/marks.rs
rust/automerge/tests/text.rs

Problem: The `AutoCommit::get_marks` call which returns the marks active for a particular index in the text returns a map from mark name to value. This map still contains marks that have been removed, just with their value set to `ScalarValue::Null`. This is inconsistent with the `marks` API and `spans` APIs which return the marks active for the whole sequence of text and do not include removed marks at all.
Solution: Update the `AutoCommit::get_marks` function to only return marks that are active for the given index.

Don't show removed marks in AutoCommit::get_marks

---

javascript/test/block_test.ts
rust/automerge/src/iter/spans.rs
rust/automerge/tests/block_tests.rs

Problem: the spans returned by `Automerge::spans` always rendered the "latest" marks in the document - i.e. the marks corresponding to the tips of the commit graph. This means that if you call `Automerge::spans_at(<some heads>)` (or, in JS,
`Automerge.spans(Automerge.view(doc, heads), <path>))` you get the correct block markers (the block markers as at the given heads), but incorrect marks (the marks as at the latest heads in the document). The reason this was happening is that in the spans iterator, which iterates over every op in the document, we correctly skip invisible ops when processing blocks, but not when processing marks.
Solution: correctly skip invisible ops when processing marks.

Fix marks in spans not respecting heads

---

javascript/packaging_tests/webpack_cjs_fullfat/package.json
javascript/packaging_tests/webpack_cjs_fullfat_next/package.json
javascript/packaging_tests/webpack_cjs_slim/package.json
javascript/packaging_tests/webpack_cjs_slim_next/package.json
javascript/packaging_tests/webpack_esm_fullfat/package.json
javascript/packaging_tests/webpack_esm_fullfat_next/package.json
javascript/packaging_tests/webpack_esm_slim/package.json
javascript/packaging_tests/webpack_esm_slim_next/package.json

Problem: when using rustc > 1.82 and webpack < 5.97.0 the wasm file generated by wasm-bindgen can't be loaded by webpack. This is tracked by an issue [1] in the wasm-bindgen repo and an issue [2] in the webpack repo. This meant that the packaging tests were failing.
Solution: upgrade the packaging tests to use webpack 5.99.0. This does mean that people using older versions of webpack will need to upgrade, but it's a patch version upgrade so shouldn't be too disruptive.
[1]: https://github.com/rustwasm/wasm-bindgen/issues/4211
[2]: https://github.com/webpack/webpack/issues/15566

js: Update webpack packaging tests to webpack 5.99.0

---

rust/automerge/src/op_set2/change/batch.rs
rust/automerge/src/op_set2/op_set.rs

Simple enough fix - optimized function wouldn't skip over marks after seeking to the starting location

seek_ops_by_index would sometimes hit marks

---

javascript/src/proxies.ts
javascript/test/proxies.ts

Problem: the indexOf method which is exposed on lists inside of a `change` callback does not handle strings correctly. For example, this test
```
let doc = Automerge.from({list: ["a", "b", "c"]})
doc = Automerge.change(doc, d => {
assert.equal(d.list.indexOf("b"), 1)
})
```
Will fail. The `indexOf` will return `-1`. The reason is that the elements of the list are represented as text objects but we compare them with native javascript strings inside `indexof`.
Solution: if the search element argument to `indexOf` is a string, check whether the candidate element is a text object and compare the search element to the reified text of the candidate element. I also commented the implementation as it was a little terse and hard to follow.

js: Fix indexOf not finding string elements

---

javascript/test/patches.ts
rust/automerge/src/automerge.rs
rust/automerge/tests/text.rs

Problem: in some scenarios it was possible for the patch logic to emit patches for elements of an object which were not actually visible. This would occur if both of these things happened:
* A change had been made to a conflicted object which was not the "winner" of the conflict
* The change was made in an interaction (e.g. a change callback, or a receive sync message) which generated a large number of patches (specifically more than 100)
In this case the patch logic would emit patches for the "loser" of the conflict, which would then be applied by the patch logic, resulting in garbled output.
The reason this was occurring is that if there are more than 100 patches to render the patch logic precomputes a cache of all the live objects in the document to avoid repeatedly traversing the …

bugfix: don't emit patches for conflicts

---

javascript/src/conflicts.ts
javascript/src/implementation.ts
javascript/test/conflicts.ts

Problem: the getConflicts call returns proxies which allow users to modify the values inside conflicted values. This is great inside a change callback but outside of a change callback it allows modifications of a document by modifying the conflicted values. This is extremely confusing as it's entirely opposite to how the rest of the API works.
Solution: detect if we are inside a change callback in `getConflicts` and if we are not, return a frozen POJO object instead of a proxy. This is much more predictable. 
As a side benefit, this fixes some tests which recently started failing due to changes in the way `assert.deepStrictEqual` treats proxies in recent node versions.

js: freeze getConflicts return value outside of change callbacks

---

javascript/src/implementation.ts
rust/automerge/src/iter/spans.rs
rust/automerge/tests/block_tests.rs
rust/automerge/tests/text.rs

Problem: the `Automerge::spans` function didn't correctly report spans with marks which crossed block markers. This was quite fiddly to debug because the logic for emitting spans is a bit complex.
Solution: clean up the spans iterator a bit so it's clearer when we're emitting spans, then always keep track of the active marks so that when we emit a block marker we don't lose the state of marks which cross the block marker.

rust: fix a bug where marks didn't cross block markers in spans

---

javascript/src/proxies.ts
javascript/test/basic_test.ts
rust/automerge-c/Cargo.toml
rust/automerge-cli/Cargo.toml
rust/automerge-test/Cargo.toml
rust/automerge-wasm/Cargo.toml
rust/automerge-wasm/src/export_cache.rs
rust/automerge-wasm/src/interop.rs
rust/automerge-wasm/src/lib.rs
rust/automerge/Cargo.toml
rust/automerge/src/op_set2/types.rs
rust/automerge/src/types.rs

Added BigInt support to the wasm and js interface.  Also fixed some issues with NaN numbers.  Note: counters going over Number.MAX_SAFE_INT will do strnage things - there wasn't a simple way to fix this due to the Automerge.Counter wrapper class so I'm deferring to a later date.

bigint support
