test/helpers.js

A few tests were failing on Node v8.2.1, where the name of an Assertion Error isn't `AssertionError`, but `AssertionError [ERR_ASSERTION]`.
This fixes that.

Fix equalsOneOf

---

test/test.js

I believe I've found a bug in Array insertion following a merge. It seems like the `actorId` affects the behaviour - with some values it works as expected, with others it doesn't.
The `lamportCompare` function sorts ops based on the `actorId`, and the result of `insertionsAfter` seems to be missing some ops depending on the alphabetical order of the two actors' `actorId`. When the `actorId` isn't specified, the behaviour is non-deterministic (because the `actorId`s are random uuids).
I haven't been able to find a fix, but hopefully these pointers will help someone more familiar with the algorithm and code find and fix the bug quicker!
Cheers,
Aslak

Test illustrating bug in Array insertion

---

README.md
src/automerge.js
src/op_set.js
test/test.js

This branch introduces two things that might not seem like they should be related, but actually are closely related:
1. Incremental cache maintenance: for example, if a change is made to a list, we make only the minimal modification to the cached list object, rather than rebuilding the whole thing after every changeset. This brings a significant performance improvement: in my test on a 1,000-element list, single-element insertion or deletion becomes about 20x faster (from about 40ms down to 2ms per operation). Still not blazingly fast, but let's just say… it's much less bad now than it was previously.
2. Computing the diff between two Automerge objects, in terms of the edits that you would need to make in order to transform the old state into the new state. This is useful for integrating …

Incremental cache maintenance & Automerge state diffing

---

package-lock.json
package.json
src/automerge.js
src/op_set.js
src/skip_list.js
test/skip_list_test.js

I have been working for a while on improving the performance of large lists (as needed for text editing = a long list of characters). This PR checkpoints the current state.
The major addition is a new data structure, an [indexed skip list](http://cglab.ca/~morin/teaching/5408/refs/p90b.pdf). The implementation here is immutable and is based on Immutable.js. Its main feature is that it gives each list element a unique ID (like our CRDT list does), and it can efficiently translate between those IDs and list indexes. All the main operations you need are O(log n): inserting a list element, deleting a list element, getting the element ID for a list index, and getting the index for an element ID.
So far, I have used the skip list only for the internal elemIds list that is part of the CRDT …

Performance: use a skip list for list element indexing

---

src/automerge.js
src/doc_set.js
src/freeze_api.js
src/op_set.js
src/proxies.js
src/text.js
test/test.js
test/text_test.js

This is the continuation of #40, improving the performance of text editing (a long list of characters). Before this PR, the slowest part of text editing was the shallow clone of the JS array holding the text that was required on every change (in order to keep it immutable). In this PR, I introduce a new datatype `Automerge.Text`, based on the skip list introduced in #40, which does not need to be cloned in order to be updated.
On a 10,000-operation text editing benchmark, the runtime is reduced to about 10 seconds, which is 7x better than the 73-second runtime before #40. The CPU time per operation is about 1 ms, which should be good enough for most practical purposes. At this point half the time is being spent in GC, and there are no obvious remaining bottlenecks in the code, so any …

Add Automerge.Text datatype

---

src/automerge.js
test/test.js

This patch defines two functions that can be used to exchange edits between Automerge nodes without using `Automerge.Connection`:
* `Automerge.getChanges(oldDoc, newDoc)` returns a list of changes that have been made in `newDoc` since `oldDoc`. You can pass `Automerge.init()` for `oldDoc` if you want to get a list of all changes ever made.
* `Automerge.applyChanges(doc, changes)` takes a list of changes produced by `getChanges`, and applies them to `doc`.
The changes are represented as JS objects including all the necessary CRDT metadata. They can be serialized to JSON and sent to another node by any network protocol.

Define getChanges/applyChanges for alternative network protocols

---

src/automerge.js
src/op_set.js
test/test.js

In some network protocols, changes are stored by actor ID. In this context, it's useful to be able to apply a change whose dependencies are not yet satisfied, and then query Automerge for the missing actor IDs and sequence numbers, so that they can be loaded and applied as well. This patch adds an API to do that: `Automerge.getMissingDeps(doc)` returns an object of actorId => seqNum.

New API to get missing causal dependencies

---

test/proxies_test.js
test/test.js

Followed the same approach from `op_set.js` and replaced
all occurrences of `'00000000-0000-0000-0000-000000000000'`
for a `ROOT_ID` constant.

Replace several empty guids for ROOT_ID constant

---

src/auto_api.js
src/automerge.js
src/immutable_api.js
src/watchable_doc.js
test/immutable_test.js

Pull request to merge in the initial version of the Immutable.js-compatible API, as discussed in #47. The feature is not complete; in particular, the Immutable.js mutation methods are not yet supported, and the feature is not yet documented. However, some intrepid early adopters are using the API, so I'm merging it so that they can depend on a released version of Automerge.

Immutable api

---

src/proxies.js
test/proxies_test.js

This makes the proxy API behave like `Array#splice`

splice in a change callback returns an array of deleted elements

---

src/freeze_api.js
test/test.js

Here is a test case, and a workaround.

Calling applyChanges twice with unresolved dependencies would throw

---

src/freeze_api.js
src/proxies.js
test/connection_test.js
test/proxies_test.js
test/test.js

This modifies both the state object and the proxy to make the `_objectId` property non-enumerable, making Automerge more developer-friendly by obscuring implementation details.
Significant updates were required to the tests, as `_objectId` was included in many assertions.  This change has the added benefit of simplifying the tests.
A test was added to cover the use of `Object.assign` (or, equivalently, the proposed object spread operator).  No additional test was necessary to verify that `_objectId` was enumerable because of the aforementioned assertions.
For more details on the motivation for this change, please the following [justification](https://gist.github.com/EthanRBrown/eb7ecc51b74170a5d415a742a6c3ca2b).

Make _objectId non-enumerable.

---

CHANGELOG.md
src/freeze_api.js

Since #83, `_objectId` is a non-enumerable property. However, the other special underscore-prefixed properties in the freeze API (`_conflicts`, `_state`, and `_actorId`) are implemented as properties of a prototype object (except for `_conflicts` on list objects, which is also a non-enumerable property). It's a bit messy that these things are inconsistent.
This patch makes all four of those underscore-prefixed properties consistently be non-enumerable properties defined with `Object.defineProperty()`; special prototype objects are no longer used.

Use object properties instead of prototype

---

.babelrc
package.json
webpack.config.js

* Configured webpack to target `umd`, which covers Node (CommonJS), global browser
use (yuck), and use with ESM (`require`)
* Configured webpack to transcompile with Babel (using `env` preset),
making suitable for use with `create-react-app`, and to generally improve
compatibility
* Configured webpack to generate source map
* Modified scripts to be more standard ("build" instead of "webpack")
* Added `prepublishOnly` script to prevent forgetful publishing of stale build (note npm 5 has deprecated `prepublish` in favor of `prepublishOnly`)
Note that without these changes, Automerge will prevent the build script in `create-react-app` from working.  That is, the following will happen:
```
$ create-react-app demo
$ cd demo
$ yarn add automerge       # or npm i
$ # edit src/App.js to "import …
```

Improved (published) package compatibility.

---

package.json
src/skip_list.js
webpack.config.js

Refactored generators to regular functions to eliminate the necessity of
a generator polyfill, which causes a lot of unfortunate distribution
overhead (i.e. the use of Babel's transform-runtime, which I have been
unable to integrate successfuly).  It also reduces the size of the
generated bundle by ~260k (over the previous use of babel-polyfill,
which I have learned is a poor choice to use in libraries).

Replaced generators.

---

src/auto_api.js
src/freeze_api.js
src/op_set.js

This PR improves the performance of changes that affect a large number of elements (map keys or list elements) of a single object within a single change block. For example, assigning a 10,000-element list:
```js
let x = [];
for (let i = 0; i < 10000; i++) x.push(i);
let doc = Automerge.change(Automerge.init(), d => d.x = x)
```
Before this PR, the code above takes about 30 seconds to run; after this patch, it takes about 3 seconds. This improvement is by replacing two accidentally-quadratic algorithms with linear-time ones.

Improve performance of bulk assignments

---

.travis.yml
package.json
yarn.lock

`yarn install` was failing on Node 10.0.0 because of the transitive dependency `karma` -> `chiokidar` -> `upath 1.0.4`, which has `engine` set to `<9`. This constraint is removed in `upath 1.0.5`, which is why I added that dev dependency. I also upgraded all other libs.

Support Node 10

---

src/automerge.js
src/doc_set.js
src/uuid.js
test/test_uuid.js

Provide a way for replacing the UUID implementation at runtime.
This is useful for writing repeatable tests, and for contexts
where an alternative source of unique IDs is prefferred.

Support replacing UUID implementation

---

src/proxies.js
test/proxies_test.js

fix #106.
This is useful in cases where I know which object I'd like to mutate, but I'm not sure where that object lives in the tree.

Expose getter for specific objects

---

src/automerge.js

getMissingChanges is necessary for writing a connector

export getMissingChanges

---

src/automerge.js
test/test.js

At the moment, the second argument to `Automerge.change()` can be not just a message describing the change, but it can in fact be any JavaScript object, and it is encoded as JSON in the serialised change data.
I am proposing changing the behaviour such that `Automerge.change()` only accepts a string as change message, and throws an error otherwise. This will pave the way towards supporting a richer API in the future, e.g. using an options object. This change also helps with the binary encoding of changes.
If you want to continue using the change message for arbitrary structured metadata can do so by doing `JSON.stringify` and passing in the result as change message.
Does anyone object to this change?

Require that the change message must be a string

---

CHANGELOG.md
src/automerge.js
src/op_set.js
test/test.js

This PR makes the changes discussed in #107:
* If the change callback doesn't actually change anything, `Automerge.change()` returns the original document object unmodified.
* If the change callback overwrites an object property with the same value, that is no longer logged as an operation.
* A new API function `Automerge.emptyChange()` exists to make a no-op change (like `git commit --allow-empty`), which can be used e.g. to capture the fact that remote changes were merged in.

Don't create a change record if nothing changed

---

backend/index.js
frontend/constants.js
frontend/index.js
src/automerge.js
test/backend_test.js
test/frontend_test.js
test/test.js

This PR fixes a bug in which sequence numbers would inadvertently get reused in the case of certain concurrency patterns between frontend and backend (see commit message on 97b9dfd6ae67ec927c846b135c399076d9284e88 for details).
Relatedly, this PR changes the data flow for undo/redo: while the actual logic remains on the backend, the responsibility for assigning sequence numbers to the undo/redo changes is moved to the frontend. This has the advantage that the frontend is now the sole authority for assigning sequence numbers, reducing the risk of further race conditions between frontend and backend.

Fix sequence number assignment

---

backend/index.js
frontend/context.js
frontend/index.js
src/automerge.js
test/backend_test.js
test/frontend_test.js

In the context of [Hypermerge](https://github.com/automerge/hypermerge), the actorId is defined to be a hypercore name, which in turn is the public key of an elliptic curve keypair and which corresponds to some files on disk. In this case, there is a noticeable cost to creating a new actorId.
For nodes that only read a document but never modify it, there is no reason to incur the cost of creating an actorId. This PR allows an Automerge document to be instantiated without assigning an actorId, as long as an actorId is assigned with `setActorId()` before any change is made to the document. To indicate that actorId assignment should be deferred, use `Automerge.init({deferActorId: true})` (if the option is not given, an actorId is automatically generated to be a random UUID, to maintain …

Allow actorId assignment to be deferred

---

backend/op_set.js

Elsewhere in the automerge we consistently throw `Error` objects rather than plain strings, so let's do the same throughout backend/op_set.js as well.

Throw error objects instead of strings in backend/op_set.js

---

backend/index.js
test/backend_test.js

If `Backend.applyLocalChange()` is called with a change request that has already been applied, it now returns a `null` patch. Previously it would return a patch with no `diffs` but with the `seq` from the request, which would throw an exception when applied to the frontend, due to the reuse of the same sequence number in different patches.

Deduplicate requests in Backend.applyLocalChange

---

frontend/index.js
src/automerge.js
test/frontend_test.js

The functions that generate requests (`Frontend.change()`, `Frontend.emptyChange()`, `Frontend.undo()`, and `Frontend.redo()`) now return a two-element array consisting of the new document state and the request object. Previously they would only return the new document state, and the request object was added to a queue that could be queried with `Frontend.getRequests()`. Since the request-generating functions now return the request directly, `Frontend.getRequests()` can be removed.
This API change encourages users of the API to send a request from the frontend to the backend only once, avoiding duplicate requests.
The `Automerge.*` public API is not affected by this change; the change is only on Frontend.

Remove Frontend.getRequests()

---

backend/index.js
backend/op_set.js
frontend/apply_patch.js
frontend/context.js
test/backend_test.js
test/frontend_test.js
test/test.js

To address #138, this patch detects when a JavaScript Date() object is assigned to an Automerge document, and converts it to an [ISO 8601 string](https://en.wikipedia.org/wiki/ISO_8601). This behaviour matches that of `JSON.stringify()`.

Support Date objects in Automerge documents

---

backend/index.js
backend/op_set.js
frontend/apply_patch.js
src/common.js
test/backend_test.js
test/test.js

This PR fixes the error reported in #145. It was caused by the MAX_ELEM list metadata being lost when a document was saved to disk and reloaded, leading to list element IDs potentially being reused.

Fix "Duplicate list element ID" error

---

README.md
backend/op_set.js
frontend/constants.js
frontend/context.js
frontend/index.js
frontend/proxies.js
src/automerge.js
test/frontend_test.js
test/proxies_test.js
test/test.js

This PR implements the long-standing request #94: Automerge map objects may now contain user-defined properties whose name begins with an underscore. Previously these properties had been reserved for Automerge-internal purposes, but now applications may use them as they see fit.
In order to enable this change, all APIs that were provided through underscore-prefixed properties or methods on document objects have now been replaced with functions in the Automerge namespace. In particular:
* `doc.object._objectId` is now `Automerge.getObjectId(doc.object)`
* `doc.object._conflicts.property` is now `Automerge.getConflicts(doc.object, 'property')`
* `doc._get(objectId)` is now `Automerge.getObjectById(doc, objectId)`

Allow property names starting with underscore

---

backend/op_set.js
test/backend_test.js
test/test.js

This PR fixes bug #151.
If a list element was added and then removed again in the same change block, then after the change came back from the backend, the frontend would forget about the element ID it had allocated. Then, on the next inserted list element, it would incorrectly reuse the same ID again. This change uses the existing maxElem action type in a patch to ensure the frontend's elemId counter is kept up-to-date.

Fixes #151: reuse of list element IDs

---

frontend/index.js
test/frontend_test.js

Bug: when using Automerge in a configuration with separate frontend and backend, attempting to perform `Frontend.undo()` would result in the following exception:
TypeError: Cannot read property 'updated' of null
at makeChange (frontend/index.js:113:43)
Fixed the bug and added tests that exercise undo/redo in the case where frontend and backend are separate.

Fix undo/redo when using separate frontend and backend

---

frontend/index.js
src/automerge.js
test/frontend_test.js
test/test.js

Returns a new document object with the given initial state. 
```js
const foo = Automerge.from({
birds: {
wrens: 3,
magpies: 4
}
})
```
Solves #127

add `Automerge.from`

---

README.md
backend/skip_list.js
frontend/apply_patch.js
frontend/index.js
src/automerge.js
test/table_test.js
test/test.js

As discovered by @izuchukwu in #177, our use of `Object.freeze` has a big negative performance impact on Automerge. In particular, in Chrome and Node (i.e. V8), copying a frozen array is [awfully slow](https://jsperf.com/cloning-frozen-array/1) (on the order of 100x slower than copying a non-frozen array of the same size), and copying a frozen object [isn't great either](https://jsperf.com/cloning-frozen-object/1). I have [filed a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=980227) that will hopefully cause this issue to be fixed, but we don't know how long it will take.
In the meantime, this PR disables the use of `Object.freeze` by default. It doesn't remove all calls to that function, but it does remove those that are on the critical path performance-wise. If …

Make use of Object.freeze optional to improve performance

---

INTERNALS.md

As I've been learning more and more about Automerge, I realized that I can help flesh out the documentation! I started to do that, but before I get carried away I want to check in on the best way to do this.
I was planning on putting up small pieces of documentation additions each day, allowing for PR review to more easily double check my work, as well as give the community the benefit of in-progress documentation. Is this helpful? Is there a different way that you'd prefer for me to contribute?

docs: Add introduction to "Applying operations to the local state"

---

backend/op_set.js

This pull request removes the `local` list from the backend. As far as I can tell, this isn't actually used anymore (I searched the codebase for `'local'`, and this was the only occurrence). If I've missed something, please help me understand what this does!

refactor: Remove unused `local` list

---

INTERNALS.md

This pull request updates the INTERNALS documentation, adding an overview of how the backend actually stores its state. There are a few specific outstanding questions that I still have; I'll call those out inline.

docs: Add local state overview

---

@types/automerge/index.d.ts
frontend/index.js
test/test.js
test/typescript_test.ts

Currently you can either call init with no arguments,
```js
const foo = automerge.init()
```
or you can pass some options around how `actorId` is set:
```js
const foo = automerge.init(actorId)
```
or
```
const foo = automerge.init({actorId, deferActorId})
```
This PR adds the (optional) options parameter to `automerge.from`, so you can do this:
```js
const foo = automerge.from(initialState, actorId)
```
or
```js
const foo = automerge.from(initialState, {actorId, deferActorId})
```
Still to do:

Add initialization options parameter to `automerge.from`

---

frontend/apply_patch.js
frontend/context.js
frontend/proxies.js
frontend/text.js
test/text_test.js

Attempt to fix #170
I'm not super happy about how code turned out as `elems` / `maxElem` are being mutated afterwards, but I also could not figure any better option. I have considered using separate field instead but that had it's own drawbacks, specifically `new Text("hello")` would have appeared as empty text.

Allow Text instatiation with preset value

---

@types/automerge/index.d.ts
test/typescript_test.ts

This PR fixes ~three~ two minor errors or omissions in the type definitions:
- `DocSet<T>` was missing `docIds` property
- `DocSet.getDoc` return value is `Doc<T>,` not `T` 
- ~Clock is a Map, not an object~
~Still to do:~

Adjustments to type definitions

---

frontend/proxies.js
test/proxies_test.js

Currently the read-only list methods such as `.map()`, `.filter()`, `.find()` and so on operate on and return plain read-only objects, as highlighted in #174. This PR changes them to operate on proxy objects instead, so that mutations of those objects are reflected on the Automerge state as expected.

List methods such as .filter() should use proxy objects

---

INTERNALS.md

This PR contains two additions to INTERNALS.md:
* There were a few operations that look like they were added after the initial implementation of Automerge, and so were missing from the internals documentation. These have been added.
* A small description about how Automerge determines causal readiness was added.

Add operations and causal readiness description too INTERNALS.md

---

frontend/text.js
test/text_test.js

I find it really confusing that `new Automerge.Text("hello").toString()` return `"h,e,l,l,o"` instead of `"hello"`. I assume this was not deliberate choice and this pull request changes to do later instead.

.toString() of Text should return a string content

---

test/test.js

Just added a couple of (passing) tests to satisfy curiosity about how concurrent deletes are handled.

Add tests for concurrent deletion

---

@types/automerge/index.d.ts
src/doc_set.js
test/docset_test.js
test/typescript_test.ts

Adds functionality to remove a doc from a `DocSet`. I'm not totally sure how the DocSet handlers work so I wasn't sure if it was appropriate to call the handlers with the deleted document's ID and `undefined`. Should that be added as well?

Add DocSet.removeDoc

---

README.md

I've been messing around with Automerge for a while now and I'm big fan, so I took a stab at writing a library to integrate PeerJS. Since MPL was a little more than I needed, and PeerJS makes working with WebRTC DataChannels dead simple, I figured this combo would be super pleasant.
Check out the project and feel free to reach out with any feedback!

Add Perge to list of Send/Receive libraries in README

---

package.json

Currently, the published package on [npm](https://npm.im/automerge) does not link to the repository.
By including those fields not only there will be a direct link, but visitors from there will also see the number of open issues and pull requests.

Include link to Github repository

---

@types/automerge/index.d.ts

We often use `type FooUrl = string & { __fooUrl: void }` to give types to different kinds of strings.
The current `Freeze<T>` type breaks these. This PR is a small fix that we've been using for awhile that has `Freeze<T>` treat these types like normal strings.

Support freezing of opaque string types

---

test/test.js

1. Moves all initialization tests to an 'initialization' `describe` block directly under 'Automerge' 
2. Adds tests for passing different types of values to `Automerge.from`: an array, a string, a number, and a boolean.

Add initialization tests for array, primitives

---

backend/index.js
frontend/index.js
src/automerge.js
test/test.js

After initializing a document with `Automerge.from()`, this patch changes the behaviour such that the initialization cannot be undone, as suggested in #219.

canUndo should return false after Automerge.from()

---

@types/automerge/index.d.ts
README.md
src/automerge.js
test/test.js
test/text_test.js
test/typescript_test.ts

Minor API usability enhancement. If you want to get a list of all changes ever made to a document, this PR introduces a new function `Automerge.getAllChanges(doc)`. It does exactly the same as `Automerge.getChanges(Automerge.init(), doc)` but is shorter, and saves having to remember the order of arguments.

New `Automerge.getAllChanges()` API

---

@types/automerge/index.d.ts
frontend/table.js
test/table_test.js
test/typescript_test.ts

This PR removes an undocumented API for adding rows to a `Table` by passing an array of values, and simplifies the type definitions for tables accordingly. 
Using the Table CRDT, you can add a row by passing an object:
```js
const ddia = doc.publications.add({
type: 'book',
authors: [martinID],
title: 'Designing Data-Intensive Applications',
publisher: "O'Reilly Media",
year: 2017,
})
```
Or, you can pass an array of values:
```js
const ddia = doc.publications.add([
'book', 
[martinID],  
'Designing Data-Intensive Applications', 
"O'Reilly Media", 
2017
])
```
Here Automerge automagically figures out which value goes in which column, based on the order of the columns provided when initializing the table. 
This array-of-values API is undocumented and, I'm guessing, unused. Supporting it in …

Simpler `Table` type

---

@types/automerge/index.d.ts
frontend/apply_patch.js
frontend/text.js
test/text_test.js

This builds on work from @pvh and @ept to allow non-string objects to be present in `Automerge.Text`. While the experiments with representing rich-text formatting by "format markers" proved unsuccessful, I think this is still useful for representing "embedded objects" within text.
Closes #194

Allow non-string children in Text objects

---

@types/automerge/index.d.ts
README.md
frontend/context.js
frontend/table.js
test/table_test.js
test/typescript_test.ts

Since #236 the Automerge.Table type no longer allows rows to be added as an array of values, which are then mapped to column names. Now that this feature is removed, nothing in Automerge is actually using the list of columns that is currently required by the Automerge.Table constructor. The columns are still saved, but since they do not enforce any schema, they are purely advisory.
Hopefully one day we can have proper schema support in Automerge, but the current half-hearted implementation is not really helping us get there. Therefore I think it is best to just remove this list of columns feature.
Any thoughts?

Remove the list of columns from Automerge.Table

---

@types/automerge/index.d.ts
CHANGELOG.md
README.md
frontend/context.js
frontend/proxies.js
frontend/table.js
test/table_test.js
test/typescript_test.ts

While we're making API changes to `Automerge.Table` anyway (#236, #241), here's another change I'd like to make.
Currently, if you have a row object from an Automerge.Table, you can get its primary key with `Automerge.getObjectId(row)`. This API is not very discoverable; users who don't know about this API might be tempted to generate their own IDs for table rows, which would miss the entire point of Automerge.Table.
This patch makes the primary key more visible by making it available as `row.id` instead. When a new row is added, we check that the row object doesn't already have an `id` property. We also ensure that the `id` property cannot be modified.
For example:
```js
let bookId
let database = Automerge.change(Automerge.init(), doc => {
doc.books = new Automerge.Table()
// the add() …
```

Make table row's primary key available as `id` property

---

@types/automerge/index.d.ts
CHANGELOG.md
frontend/apply_patch.js
frontend/table.js
test/table_test.js

The `set()` method is not needed, since `add()` and `remove()` handle changes to the set of rows, and properties of row objects can be updated directly without requiring any `set()` operation at the table level. The method may lead to confusion, as in #228.
Looking at the code, I now realise that `set()` was not intended to be part of the public API at all: it is called while applying a patch, and if a user calls it, it does not generate any operations in the change
context. Hence I renamed it to start with an underscore (like `_clone()` and `_freeze()`), and added a warning to the comment.

Remove set() method from Automerge.Table API

---

@types/automerge/index.d.ts

The `rows` here is a property getter and not a function that can be called from what I can see [here](https://github.com/automerge/automerge/blob/14409f01adae1778c76ca13e7432f395fea4db54/frontend/table.js#L60-L66). As it is right now I can't use it since TypeScript think it's a function and calling gives an error.

Update table class type to reflect property getter

---

@types/automerge/index.d.ts

This change reflects the internal implementation, it's also consistent with the `DocSet#set` and `DocSet#get` signatures

Fix type signatures for WatchableDoc#get and WatchableDoc#set

---

frontend/proxies.js
test/proxies_test.js

The parameter to `[].indexOf(...)` may be a Proxy object. In that case, the correct index should be returned. Currently it always returns `-1`.

support calling indexOf with an object

---

README.md

The current link points to a fork.

README: Update pushpin link

---

frontend/proxies.js
test/proxies_test.js

Before to this patch, calling `splice` on an Automerge list with a
deleteCount that overflows the list results in a RangeError.
However, according to Mozilla's documentation (and tested on Node
v14.15.4), splice's `deleteCount` argument can be equal or greater than
the list. In that case, all the elements from start to the end of the
array should be deleted.
With this patch, deleteCount can overflow the list's length and the
behaviour is like no deleteCount was passed.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

frontend: splice's deleteCount can overflow

---

BINARY_FORMAT.md
backend/columnar.js
backend/op_set.js
frontend/apply_patch.js
frontend/context.js
frontend/index.js
frontend/proxies.js
src/common.js
test/backend_test.js
test/columnar_test.js
test/context_test.js
test/frontend_test.js
test/fuzz_test.js
test/proxies_test.js
test/table_test.js
test/test.js
test/typescript_test.ts
test/wasm.js

This PR makes a bunch of small, but breaking changes to the data formats (both binary and JSON representation). The intention is to clean up a bunch of minor annoyances, and to get our breaking changes out of the way now before we make commitments to the data formats we will support long-term.
Brief summary of the changes made (see the commit messages for details):
* Use the string `'_root'` instead of the all-zeros UUID in changes and patches (10ec271cbd66955390cd5c0b3ab22def76302f44)
* On operations that change a list or text object, use the property `elemId` instead of the property `key` to identify the list element being updated (6fa8b5a5b9bbfb178750c629fc6107b30b9c35a3)
* Reorder some of the fields in the binary encoding to make it easier and faster to parse …

Tweaks to data formats

---

@types/automerge/index.d.ts
CHANGELOG.md
frontend/apply_patch.js
frontend/context.js
frontend/index.js
frontend/observable.js
frontend/text.js
src/automerge.js
test/observable_test.js
test/test.js
test/text_test.js
test/typescript_test.ts

There have been requests for an observer-style API, where an application's callback function gets called whenever a certain part of an Automerge document changes. For example, this is useful when integrating a text editing widget with Automerge, where the widget state needs to be updated whenever the Automerge document changes (especially as a result of remote changes arriving from the network).
This PR is based on #288, allowing hooking into patch application, but based on the performance branch rather than main. Moreover, I've extended the API with a new class `Automerge.Observable`, which allows observing individual objects as well as the entire document. The callback is given a description of the change in the [Automerge patch …

Experimental observable API

---

frontend/text.js
test/text_test.js

Creating a text with a unicode character results in the unicode characted being split. If used with the rust backend it results in an ugly runtime error.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split
There is a warning in there:
> Warning: When the empty string ("") is used as a separator, the string is not split by user-perceived characters (grapheme clusters) or unicode characters (codepoints), but by UTF-16 codeunits. This destroys surrogate pairs. See “How do you get a string to a character array in JavaScript?” on StackOverflow.
I did not do an extensive check of the codebase for this issue, just fixed the most critical path for us at this point.

Support creating text with unicode chars

---

backend/columnar.js
package.json
test/backend_test.js
test/columnar_test.js
test/wasm.js
yarn.lock

This PR adds support for DEFLATE compression. As explained in #317, compression can be used in two places:
* On an individual change, the whole change can be compressed. The change hash is computed on the uncompressed change, and the checksum included in the change is based on the uncompressed change. We do this because two different compressors given the same input do not necessarily produce the same compressed byte stream.
* On a compressed document, one column at a time can be compressed. I changed the definition of the columnId to reserve one bit to indicate whether the column is compressed. We do this so that it is possible to load only a subset of columns of a document.
Compression is only enabled when the data is larger than some threshold (currently 256 bytes) since it's not worth …

Add DEFLATE compression

---

backend/backend.js

Was running a benchmark doing 1 char insert per change over 50,000 chars and it ran in 80 seconds - this change makes it run in 16 seconds.

Speedup hashesbyactor

---

@types/automerge/index.d.ts
backend/backend.js
backend/columnar.js
backend/op_set.js
frontend/apply_patch.js
frontend/context.js
frontend/index.js
frontend/observable.js
src/common.js
test/backend_test.js
test/context_test.js
test/frontend_test.js
test/observable_test.js
test/sync_test.js
test/test.js
test/typescript_test.ts

This is a first shot at implementing the new sequence patch format outlined in #311. It's mostly working with the exception of the Observable API. I need to spend some time figuring that out but I wanted to get some eyes on this first.
There is one outstanding question I have which relates to the value of the pred attribute for multiOp delete operations. Consider this operation:
```javascript
{
obj: listId, 
action: 'del', 
elemId: '1@xxx', 
multiOp: 2,
insert: false,
}
```
In order for this to work we need to specify the predecessor operations for each element being overwritten. The approach I've gone for in this patch is to flatten the predecessor IDs for the whole set of deleted list elements into one pred array and attached it to the op. This works but it feels clumsy and belies the …

Implement the new sequence patch format, fixes #311

---

backend/sync.js
package.json
test/sync_test.js

What I'm trying to simulate here is if one node loses all of it's data including document data as well as any previous sync state information.
The test i've created here goes into an infinite loop.  I believe I'm experiencing this in a real world app but I'm not 100% sure I've captured it accurately in the test.
I'm wondering if this is something application developers should be proactive about (sending a sync message for a blank document) or if this is an actual bug in the sync protocol.
I am able to sync these docs when they both reset their sync state to `initialSyncState()`.  So the question is how should the node that has intact state react to the "bad" sync request from the errant peer?
EDIT: I made the test pass but I'm not sure what kind of damage my "fix" may have caused.  It …

Sync fails if one node experiences complete data loss but another node has a stale sync state

---

backend/columnar.js
test/backend_test.js
test/columnar_test.js
test/wasm.js

This fixes some of the wasm tests that I'm finding issues with while implementing the new patch format in https://github.com/automerge/automerge-rs/pull/88.
Seems it also brings to light some missing `type: 'value'`s in the js code too. (I'd appreciate someone with more intimate knowledge of the js implementation to help me with the errors here as trying to change a couple of the places in the code makes more things fail).

Fix wasm tests

---

backend/op_set.js

Automerge 1.0.1-preview.0 has been occasionally (hard to consistently reproduce) crashing for me with the following message:
```
TypeError: Not a byte array: [object Object]
at new Decoder (automerge-backend/node_modules/automerge-preview/dist/webpack:/Automerge/backend/encoding.js:304:13)
at decodeChangeMeta (automerge-backend/node_modules/automerge-preview/dist/webpack:/Automerge/backend/columnar.js:778:40)
at map (automerge-backend/node_modules/automerge-preview/dist/webpack:/Automerge/backend/sync.js:263:20)
at Array.map (<anonymous>)
at getChangesToSend (automerge-backend/node_modules/automerge-preview/dist/webpack:/Automerge/backend/sync.js:263:6)
```
After some debugging I found out that even though the `Decoder` constructor expects an `ArrayBuffer`, it would sometimes be passed an …

Fix invalid opSet getMissingChanges return value

---

backend/op_set.js
test/sync_test.js

@skokenes I think this fixes your issue #367. Could you give it a try please?
In a history with a lot of branching and merging, the slow path algorithm in `OpSet.getMissingChanges` would traverse a number of paths that grows exponentially in the length of the history. Ooops! Should have been O(n), was actually O(2^n). No wonder it would grind to a halt.

Fix performance issue in OpSet.getMissingChanges

---

@types/automerge/index.d.ts
backend/backend.js
backend/index.js
backend/op_set.js
package.json
src/automerge.js
webpack.config.js
yarn.lock

Previously, `Automerge.merge(localDoc, remoteDoc)` would get all changes from `remoteDoc` and apply them to `localDoc`, relying on the built-in change deduplication to ignore any changes already present in `localDoc`. This works but is quite slow. This PR changes `merge` to get only those changes in `remoteDoc` that are not already present in `localDoc`, and applies those.
On @josephg's benchmark in #360 this improves performance by a factor of 15 on my machine:
* Automerge 0.14.1: about 7,100 iterations in 5 seconds
* Automerge 1.0.1-preview.1: about 300 iterations in 5 seconds
* With this PR: about 4,700 iterations in 5 seconds
Note this PR introduces a new backend function `getChangesAdded()`, which will also need to be implemented in the Rust backend.

Improve performance of repeated calls to `Automerge.merge()`

---

backend/sync.js
test/sync_test.js

This PR fixes a bug reported by @skokenes. He was occasionally getting the following exception:
TypeError: Cannot read property '8' of undefined
at decodeChangeMeta (backend/columnar.js:783:13)
at /Users/martin/dev/cl/automerge/backend/sync.js:383:62
at Array.filter (<anonymous>)
at Object.generateSyncMessage (backend/sync.js:383:33)
at Object.generateSyncMessage (src/automerge.js:125:18)
I tracked it down to the following situation in the sync protocol. Say you have two nodes n1 and n2 that are syncing their changes, and due to a Bloom filter false positive n2 doesn't send some change that n1 needs, so n1 now has a missing dependency (what we sometimes call a "hole").
Now before n1 and n2 are able to fill in the missing dependency and complete their sync, n1 also performs a sync with a …

Syncing with a third node when one node has a missing dependency

---

backend/columnar.js
test/backend_test.js
test/columnar_test.js

To ensure the change encoding is canonical and unambiguous, avoiding bugs such as automerge/automerge-rs#145.

Require strictly ordered preds in change ops

---

.eslintrc.json
package.json
webpack.config.js
yarn.lock

Adds linting to detect usage of features that are not natively supported by our target platforms. Sets those platforms using https://github.com/browserslist/browserslist but we should negotiate what those platform ought to be before merging this—I picked this list as a sensible starting point.
We should also update the docs to let consumers know what sort of environments are supported.
**Note**: @babel/preset-env also uses this same setup as the target of its transpilation and polyfilling, so we will want to check the output of the bundling and transpilation to ensure it does not include any performance regressions. See #368 for some babel-related discussion that is relevant here.
Closes https://github.com/automerge/automerge/issues/370

Add `eslint-plugin-compat` and update linting config

---

webpack.config.js

The browser tests broke during the refactor at #396 complaining about not being able to iterate over undefined "chunks":
```
Uncaught TypeError: Cannot read property 'webpackChunkAutomerge' of undefined
```
That reminded me of the issue that was noted in that original PR where setting this `chunkLoading` property didn't seem to make a difference for running webpack, but it looks like it _does_ matter for actually using the bundle! 😅 
I've run `yarn run browsertest` locally and it seems to work, so hopefully this fixes the issue.

Do not chunk the output in webpack config

---

karma.conf.js
src/uuid.js
tsconfig.json

Deep importing from the `uuid` library is [deprecated](https://github.com/uuidjs/uuid#deep-requires-now-deprecated) and [breaks](https://github.com/uuidjs/uuid/issues/575) some browser builds.

Use named imports for the uuid library

---

@types/automerge/index.d.ts

Hey!
It looks like `elemId` is missing from TypeScript definition of `Op`. 
What's weird is that it's actually included in the JS object, e.g. if you do `JSON.stringify(operation)`:
```
{"obj":"2@c8016fb46d8a4093aebefa23af4b6af1","elemId":"4@c8016fb46d8a4093aebefa23af4b6af1","action":"makeMap","insert":true,"pred":[]}
```
But you can't access it in TypeScript, because it's missing from `Op`. 
Ideally, we'd like to have an access to `elemId` to be able to "interpret" changes without using automerge methods (e.g. in a different runtime). Without `elementID` it becomes problematic (if not impossible).
So in this PR I've added `elemId` property to the list of attributes for a TS representation of `Op`.

Include `elemId` into TypeScript definition of `Op`

---

@types/automerge/index.d.ts

(follow-up on #424 and #426, sorry for that excessive granularity, I'm discovering missing fields as I go deeper into B-F protocol)
Related to #429.
`hash` field stores SHA-256 of a binary encoding of change. It's used to fill up `deps` of the following changes. However, it's missing from TS definition of `Change`, but present in the plain JS object:
```
{
"actor": "76606470dee9469391163cb3c43c220a",
"seq": 2,
"startOp": 2,
"time": 1629452632,
"message": "",
"deps": [
"f81149f2a77edb5425d64966151d3f8d66a30a907ed29760a47e4c2805439169"
],
"hash": "ae910c6f52b09c9f256be9cc9ba4f5925c8fcb5066c81a4faac226e547e4a8df",
"ops": [...]
```
So here we expose it, but make it optional, since it's backend responsibility to fill it.

Include `hash` to TypeScript definition of `Change`

---

backend/encoding.js
test/new_backend_test.js

This should fix issue #441. @cgauld, please could you give it a try?

Fix exception "Zero-length runs are not allowed" in BooleanDecoder

---

backend/new.js
test/test.js

Fixes #445
Thanks @okdistribute for reporting the issue. The problem was as follows:
When applying changes we need to detect and ignore any duplicate changes that we've already applied. We do this by checking the change hash against a set of known hashes. However, we try to avoid computing the full hash graph when loading a compressed document, in which case we are not able to accurately detect duplicates, since we don't know most of the hashes.
This patch changes the logic so that when we suspect there is a duplicate change (on the basis of its sequence number), and we haven't already computed the hash graph, then we go ahead and compute the hash graph in order to know for sure whether it's a duplicate or an illegal sequence number reuse. This means we incur the hash graph computation …

Fix deduplication of changes after loading compressed document

---

backend/new.js
test/test.js

The new backend did not compute the maxOp property of a change that had no operations, which would cause an exception later when a subsequent change, or the whole document, was encoded. This fixes the issue. Thanks to @jrakow for reporting it.
Fixes #456

Fix encoding of document containing an empty change

---

backend/new.js
test/test.js

There was a bug that meant that if applyChanges was called with changes in an order that was inconsistent with the dependencies between the changes, only some of the changes would get applied. Other changes would remain in the queue even though they were ready to be applied. This PR fixes the bug.

Fix out-of-order change application

---

test/test.js

Had a bug in the rust version with lamport ordering being wrong - none of the tests caught it - here are a few that would have caught this sooner.

explicitly expose Lamport ordering in a test

---

README.md
src/automerge.js

When I chatted with @ept he mentioned that the restriction is artificial and was put there to stop people accidentally misusing the API. Unfortunately it is a limitation for certain use-cases.
My use-case: I'm having an end-to-end encrypted protocol where `save` is leveraged to create Snapshots of the current document that are stored remotely. Now if a client has a
- local version
- fetches the latest snapshot to apply it
You can't merge the documents together. I also can imaging architectures that leverage `save` to place document into different storages and need to merge them.
Of course this already is an advanced use-case and could be worked around directly leveraging `applyChanges`. 
Let me know if you think the restriction is important enough or it's fine to remove.
_Note_: `yarn …

remove limitation that merge requires different actors

---

@types/automerge/index.d.ts

See https://github.com/automerge/automerge.github.io/issues/16 for a description of the issue.
Make the change function work like the other type declarations (like
applyChanges, applyPatch, etc.) where the user just specifies
the plain type `T` as a type param and the function returns
a `Doc<T>` (which is shorthand for a `FreezeObject<T>`).
For consistency it looks like the same change could also be applied to `getHistory` and maybe `emptyChange` (but I haven't used those yet, so not sure).  Then that `Proxy<T>` type could potentially be removed.  I think what it's trying to convey can be conveyed better in other ways.

Update type declaration for `change` function for consistency

---

LICENSE

With this update, you won't care about any further license year updates
Using present instead of the second year is a common pattern, here are some examples
https://github.com/babel/babel/blob/4fb29a372b18e82ba72262db43b80b220a5cce01/LICENSE#L3 https://github.com/reduxjs/redux/blob/8ad084251a5b3e4617157fc52795b6284e68bc1e/LICENSE.md?plain=1#L3 https://github.com/pmndrs/react-spring/blob/e7d423cde197db9d53a00f96422c6d7f8ce12b29/LICENSE#L3 https://github.com/vercel/styled-jsx/blob/e8245813f9c3e633a9b2d2414fb11e6386b31216/license.md?plain=1#L3 https://github.com/styled-components/styled-components/blob/09929bd9bc05da085206c94679f07597b46212e4/LICENSE#L3

Update LICENSE for present
