automerge-backend-wasm/src/lib.rs, automerge-backend-wasm/tests/app.rs, automerge-backend/src/backend.rs, automerge-backend/src/concurrent_operations.rs, automerge-backend/src/lib.rs, automerge-backend/src/object_store.rs, automerge-backend/src/op_set.rs, automerge-backend/src/patch.rs, automerge-backend/src/patch_serialization.rs, automerge-backend/src/protocol.rs, automerge-backend/src/protocol_serialization.rs, automerge/src/change_context.rs
I got the tests passing but need help getting the code clean and idiomatic. Also I got `InsertSequenceElement.after` working but I think by accident.  Could you feedback on how it should behave since you wrote the other code around it.
=> all get_patch tests passing

automerge-cli/IDEAS.md
As discussed with @alexjg , we want to tackle mutation next, so added some examples for `set` and `get`.
=> cli: Add mutation CLI subcommands to IDEAS documentation

automerge-backend-wasm/src/lib.rs, automerge-backend/src/backend.rs, automerge-backend/src/change.rs, automerge-backend/src/columnar.rs, automerge-backend/src/error.rs, automerge-backend/src/op_set.rs, automerge-backend/src/pending_diff.rs, automerge-backend/tests/apply_change.rs, automerge-frontend/src/state_tree/mod.rs, automerge-frontend/src/value.rs, automerge-protocol/src/lib.rs, automerge-protocol/src/serde_impls/cursor_diff.rs, automerge-protocol/src/serde_impls/diff.rs, automerge-protocol/src/serde_impls/mod.rs, automerge-protocol/src/serde_impls/op.rs, automerge-protocol/src/utility_impls/element_id.rs, automerge-protocol/src/utility_impls/scalar_value.rs
Backend implementation of https://github.com/automerge/automerge/pull/313
=> Cursors backend

automerge-frontend/src/mutation.rs
=> Change Increment operation to use i64

automerge-cli/src/change.rs, automerge-frontend/benches/change.rs, automerge-frontend/src/lib.rs, automerge-frontend/tests/test_backend_concurrency.rs, automerge-frontend/tests/test_cursor.rs, automerge-frontend/tests/test_frontend.rs, automerge-frontend/tests/test_mutation.rs, automerge-frontend/tests/test_wasm.rs, automerge/benches/crdt_benchmarks.rs, automerge/tests/save_load.rs
=> Allow change to return value from users closure

.travis.yml
This makes the final stage of CI work.
=> Add newer version of nodejs

Cargo.nix, flake.lock, flake.nix
Updates the dependencies, adds some checks (for `nix flake check`) and adds `automerge-cli` as an application (for `nix run .#automerge-cli`).
=> Update nix config

automerge-backend/src/backend.rs
Had to hand copy code over - created some tests - broke the fast path into its own function to test
=> get changes fast

automerge-c/automerge.c, automerge-c/automerge.h, automerge-c/src/lib.rs
For testing, I copied the "test_not_reply_if_we_have_no_data_as_well" test from the JS frontend.
=> Add C bindings for sync functions

automerge-backend-wasm/src/lib.rs, automerge-backend/src/backend.rs, automerge-backend/src/change.rs, automerge-c/automerge.h, automerge-c/src/lib.rs
Implemented getAddedChanges which was in the JS backend, but not the Rust backend.
Not sure how to test this b/c many of the JS interop tests are failing right now due to  this (https://github.com/automerge/automerge-rs/commit/87410e4c8fe2a295c0c66e413f0451649193f541) I assume.
=> Implement getAddedChanges

automerge-backend/src/columnar.rs
=> Sort predecessors during encoding

automerge-c-v2/Cargo.toml, automerge-c-v2/automerge.c, automerge-c-v2/automerge.h, automerge-c-v2/src/lib.rs
This updates the C bindings to use msgpack.
=> C bindings msgpack

automerge-backend-wasm/Cargo.toml, automerge-backend/src/change.rs
Simple fix to remove deflate bit from column decode
=> fix deflate column decode order

automerge-frontend/src/state_tree/mod.rs, automerge-frontend/src/state_tree/multivalue.rs, automerge-frontend/src/state_tree/resolved_path.rs
This helps to squeeze out some more performance on map heavy documents.
=> New value zero copy multivalue

automerge-backend/src/change.rs, automerge-backend/src/columnar.rs, automerge-backend/src/object_store.rs, automerge-backend/src/op_set.rs, automerge-backend/src/patches/from_scratch_diff.rs, automerge-backend/src/patches/incremental_diff.rs, automerge-backend/tests/apply_change.rs, automerge-backend/tests/apply_local_change.rs, automerge-backend/tests/get_patch.rs, automerge-frontend/benches/statetree_apply_diff.rs, automerge-frontend/src/state_tree/mod.rs, automerge-frontend/src/state_tree/multivalue.rs, automerge-frontend/src/value.rs, automerge-frontend/tests/test_apply_patch.rs, automerge-frontend/tests/test_backend_concurrency.rs, automerge-frontend/tests/test_cursor.rs, automerge-frontend/tests/test_frontend.rs, automerge-frontend/tests/test_mutation.rs, automerge-protocol/src/lib.rs, automerge-protocol/src/serde_impls/diff.rs, automerge-protocol/src/serde_impls/op.rs, automerge-protocol/src/serde_impls/op_type.rs, automerge-protocol/src/utility_impls/diff.rs, automerge-protocol/tests/serde_round_trip_proptest.rs, automerge/tests/frontend_backend_roundtrip.rs, automerge/tests/save_load.rs
Fixes https://github.com/automerge/automerge-rs/pull/168#issuecomment-860846059
=> Flatten objtype

automerge-backend/src/sync.rs
Fixes https://github.com/automerge/automerge-rs/issues/151
=> Stop non-empty needs repeating messages

Makefile
This should allow consistent commands for everyone, including a local ci
check.
=> Add makefile for ease of use

.travis.yml, automerge-backend/src/backend.rs, automerge-backend/src/change.rs, automerge-backend/src/columnar.rs, automerge-backend/src/encoding.rs, automerge-backend/src/event_handlers.rs, automerge-backend/src/op_set.rs, automerge-backend/src/ordered_set.rs, automerge-backend/src/patches/edits.rs, automerge-backend/src/patches/incremental_diff.rs, automerge-backend/src/sync.rs, automerge-backend/src/sync/bloom.rs, automerge-cli/src/examine.rs, automerge-cli/src/import.rs, automerge-frontend/Cargo.toml, automerge-frontend/src/state_tree/diffable_sequence.rs, automerge-frontend/src/state_tree/mod.rs, automerge-frontend/src/state_tree/multivalue.rs, automerge-frontend/src/state_tree/resolved_path.rs, automerge-protocol/Cargo.toml, automerge-protocol/src/lib.rs, automerge-protocol/src/serde_impls/diff.rs, automerge-protocol/src/serde_impls/op.rs, automerge-protocol/src/serde_impls/root_diff.rs
A bunch of cleanup.  There are still two issues.  On the frontend there are some errors around `arbitrary::Arbitrary` not playing nicely with `smol_str::SmolStr`.  Also two tests are breaking in the wasm/js interop related to sync.  Anyone know where this came from?
=> Fix Clippy issues, broken tests, formatting issues

automerge-backend/src/change.rs, automerge-backend/src/columnar.rs
This results in a performance boost due to doing less allocation but also should be more memory efficient.
=> load: Reduce intermediate collects and use iterators more

automerge-frontend/src/state_tree/diffable_sequence.rs
This makes it so that rebalancing moves less data around thus making the
trace benchmark twice as fast!
I can't believe I didn't try it sooner...
=> diffable seq: Box Vector contents

automerge-frontend/src/value.rs, automerge-frontend/src/value/conflicts.rs, automerge-frontend/src/value/cursor.rs, automerge-frontend/src/value/primitive.rs
These methods make operating on the values easier in some situations.
=> Add is_* and extraction methods to Value and Primitive

automerge-frontend/src/state_tree/mod.rs, automerge-frontend/src/state_tree/multivalue.rs, automerge-frontend/src/value.rs, automerge-frontend/tests/test_frontend.rs, automerge-frontend/tests/test_mutation.rs, automerge-frontend/tests/test_wasm.rs, automerge/benches/save_load.rs, automerge/benches/sync.rs, automerge/tests/frontend_backend_roundtrip.rs, automerge/tests/save_load.rs
=> Rename Sequence to List

TODO.md, automerge-js/src/constants.js, automerge-js/src/index.js, automerge-js/src/proxies.js, automerge-wasm/src/lib.rs, automerge-wasm/test/test.js, automerge/src/clock.rs, automerge/src/lib.rs, automerge/src/op_set.rs, automerge/src/op_tree.rs, automerge/src/query.rs, automerge/src/query/insert.rs, automerge/src/query/keys.rs, automerge/src/query/keys_at.rs, automerge/src/query/len.rs, automerge/src/query/len_at.rs, automerge/src/query/list_vals.rs, automerge/src/query/list_vals_at.rs, automerge/src/query/nth.rs, automerge/src/query/nth_at.rs, automerge/src/query/prop.rs, automerge/src/query/prop_at.rs, automerge/src/query/seek_op.rs, automerge/src/types.rs
I got all the `query_at(heads)` implemented.  Wrote a bunch of tests and they all pass.  All of these do sequential scans so they aren't super fast but they get the job done.  Also removed a bunch of dead code.
=> `query_at(heads)`

.github/workflows/advisory-cron.yaml, .github/workflows/ci.yaml, LICENSE, README.md, automerge-wasm/Cargo.toml, automerge/Cargo.toml, automerge/src/decoding.rs, automerge/src/legacy/serde_impls/op.rs, automerge/src/lib.rs, automerge/src/op_set.rs, automerge/src/op_tree.rs, automerge/src/query/insert.rs, automerge/src/query/nth.rs, automerge/src/visualisation.rs, automerge/tests/helpers/mod.rs, automerge/tests/test.rs, deny.toml, edit-trace/Cargo.toml, scripts/ci/advisory, scripts/ci/build-test, scripts/ci/docs, scripts/ci/fmt, scripts/ci/lint, scripts/ci/run
This adds a bunch of CI steps. There were a few changes I had to make to the code to get clippy and rustfmt to stop complaining. I've also added a deny.toml and run `cargo deny *` to make sure we're not duplicating dependencies or pulling in insecure dependencies.
The biggest thing to review is that I've added an MIT license to all the crates. I think we all (me, @orionz, @jeffa5 ) need to agree to that here. This PR is my endorsement of the license.
=> Ci ci oh how i love ci

TODO.md, automerge-js/src/index.js, automerge-js/src/proxies.js, automerge-js/test/sync_test.js, automerge-wasm/package.json, automerge-wasm/src/interop.rs, automerge-wasm/src/lib.rs, automerge-wasm/src/sync.rs, automerge-wasm/src/value.rs, automerge-wasm/test/helpers/columnar.js, automerge-wasm/test/helpers/common.js, automerge-wasm/test/helpers/encoding.js, automerge-wasm/test/helpers/sync.js, automerge-wasm/test/test.js, automerge/src/automerge.rs, automerge/src/sync.rs, automerge/src/sync/state.rs, automerge/src/types.rs
Got all the javascript sync tests passing - found one bug in the rust - cleaned up and added some features to the wasm api - hand ported all the old sync tests over to wasm.  Mostly js changes but if felt pretty beefy and wanted to get feedback before merging.
=> Sync fixes

automerge/src/op_set.rs
This is a minor refactor and is paving the way toward index query caching for a speedup down the road.  Also fixes a small bug where a rollback could confuse the op_set op iterator (by having an empty optree)
=> refactor how op_set manages objects

automerge-backend/Cargo.toml, automerge-backend/src/change.rs, automerge-backend/src/columnar.rs, automerge-backend/src/decoding.rs, automerge-backend/src/ordered_set.rs, automerge-backend/tests/apply_change.rs, automerge-cli/Cargo.toml, automerge-cli/src/main.rs, automerge-frontend/Cargo.toml, automerge-protocol/Cargo.toml, automerge/Cargo.toml, automerge/tests/frontend_backend_roundtrip.rs, automerge/tests/save_load.rs
Cleaned up `main` by compiling against Rust 1.58.1 and:
* Cleaning up warnings
* Upgrading packages to most recent version
* Fixed some errors
All tests pass
=> Cleaned up some warnings and errors running against Rust 1.58.1

automerge/examples/README.md, automerge/examples/quickstart.rs, automerge/src/automerge.rs, automerge/src/change.rs
Really this branch is based on https://github.com/automerge/automerge-rs/pull/271.
=> Add quickstart example using new transaction

automerge-wasm/Cargo.toml, automerge/Cargo.toml, automerge/src/automerge.rs, automerge/src/error.rs, automerge/src/lib.rs
Make a wasm feature flag - conditional dependencies for js_sys and wasm-bindgen
=> move wasm to feature flag

automerge-wasm/src/interop.rs, automerge/src/change.rs, automerge/src/lib.rs
This should be associated with the change type, not just being a free function.
=> Make decode_change an associated function

automerge/src/value.rs
Adds conversions to contained types, is_* methods for checking the
variant and conversions from more types.
=> Cleanup value API

automerge-c/src/CMakeLists.txt, automerge-c/src/lib.rs
@orionz, this PR makes my last round of changes pass the `$ ./scripts/ci/fmt` workflow step.
=> Fix "fmt" workflow step violations

automerge-wasm/test/attribute.ts
This is a test for the attribution code that confirms that it does not surface changes that "never occur" on baseline.
e.g., given two heads, h1 and h2, if a set of changes are applied to h2:
```
h2 = h1.fork()
h2.splice(text, 0, 0, "xyz")
h2.splice(text, 0, 3, "")
```
Neither `add: { start 0, end: 3 }` nor `del: { pos: 0, val: "xyz" }`  should not occur in the attribution set.
We thought they might, but this test confirms they don't. Adding tests here to proactively prevent any possible regressions.
=> Additional Attribution Tests

automerge/src/automerge.rs, automerge/src/keys.rs, automerge/src/keys_at.rs, automerge/src/op_set.rs, automerge/src/op_tree.rs, automerge/src/query.rs, automerge/src/query/insert.rs, automerge/src/query/keys.rs, automerge/src/query/keys_at.rs, automerge/src/query/len.rs, automerge/src/query/len_at.rs, automerge/src/query/list_vals.rs, automerge/src/query/list_vals_at.rs, automerge/src/query/nth.rs, automerge/src/query/nth_at.rs, automerge/src/query/opid.rs, automerge/src/query/prop.rs, automerge/src/query/prop_at.rs, automerge/src/query/seek_op.rs, automerge/src/query/seek_op_with_patch.rs, automerge/src/sequence_tree.rs, automerge/src/visualisation.rs
This doesn't need to be generic on everything, just defined once as a
const and referenced.
=> Remove const B: usize requirement everywhere

automerge/src/automerge.rs
I think this was just missed off.
=> Add object replacement character in text_at

automerge/src/decoding.rs, automerge/src/encoding.rs, automerge/src/error.rs, automerge/src/transaction/inner.rs, automerge/tests/test.rs
=> Prevent increment on non-counter

automerge-c/examples/quickstart.c, automerge-c/src/lib.rs, automerge-c/test/group_state.c
@orionz, I've made the changes that you requested.e.g.
* Renamed `AMalloc()` to `AMcreate()`.
* Renamed `AMload()` to `AMloadIncremental()`.
* Added the `AMload()` function.
=> C API symmetry improvements

automerge-c/src/doc.rs, automerge-c/src/doc/list.rs, automerge-c/src/doc/map.rs, automerge-c/src/result.rs, automerge-c/src/sync/state.rs, automerge-c/test/CMakeLists.txt, automerge-c/test/doc_tests.c, automerge-c/test/list_tests.c, automerge-c/test/main.c, automerge-c/test/map_tests.c
@orionz, I've added most of the functions from the automerge-c/README.md that were missing from the C API.
=> Add some functions from the README.md file

automerge-js/e2e/verdaccio.yaml, automerge-wasm/src/lib.rs, automerge/examples/quickstart.rs, automerge/examples/watch.rs, automerge/src/autocommit.rs, automerge/src/automerge.rs, automerge/src/automerge/tests.rs, automerge/src/transaction.rs, automerge/src/transaction/inner.rs, automerge/src/transaction/manual_transaction.rs, automerge/src/transaction/observation.rs
Most of the details are in the commit messages
=> Opobserver type trickery

flake.lock, flake.nix
Mainly updates the flake to use a newer Rust version.
=> Update nix flake and add formatter and dead code check

rust/automerge/src/op_tree.rs, rust/automerge/src/op_tree/iter.rs, rust/automerge/src/op_tree/node.rs, rust/automerge/src/query.rs, rust/automerge/src/query/elem_id_pos.rs, rust/automerge/src/query/insert.rs, rust/automerge/src/query/keys.rs, rust/automerge/src/query/keys_at.rs, rust/automerge/src/query/len.rs, rust/automerge/src/query/list_range.rs, rust/automerge/src/query/list_range_at.rs, rust/automerge/src/query/list_vals.rs, rust/automerge/src/query/map_range.rs, rust/automerge/src/query/map_range_at.rs, rust/automerge/src/query/nth.rs, rust/automerge/src/query/opid.rs, rust/automerge/src/query/opid_vis.rs, rust/automerge/src/query/prop.rs, rust/automerge/src/query/prop_at.rs, rust/automerge/src/query/seek_op.rs, rust/automerge/src/query/seek_op_with_patch.rs, rust/automerge/src/visualisation.rs, rust/edit-trace/automerge-js.js, rust/edit-trace/automerge-wasm.js, rust/edit-trace/package.json, rust/edit-trace/src/main.rs
No performance difference on rust/IA64 but a 25% uplift in WASM/IA64, 40% on WASM/M1 and a 5% uplift on rust/M1.
=> Rewrote OpNode to store indexs and then look up Op

rust/automerge/src/query/seek_op.rs, rust/automerge/tests/test.rs
The `SeekOp` query can produce incorrect results when the optree it is searching only has visible ops on the internal nodes. The issue is that in the `SeekOp` we skip an entire child node if it only contains invisible ops. Consider this optree:
In this optree the only visible ops for the "a" key and "b" key are in the non-leaf node. This means that when we query for the insert position for a new op on the "a" key we seek past the first node, but then because the next child node does not contain any visible ops either, we seek past it to the next child, even though none of the ops in it are for "a", consequently we end up calculating that the insert index should be 31,  rather than 16.
This problem has raised it's head when loading saved documents which were generated from such situations. …
=> Correctly handle ops on optree node boundaries

rust/automerge/src/query/seek_op.rs, rust/automerge/src/query/seek_op_with_patch.rs
In #480 we fixed an issue where `SeekOp` calculated an incorrect insertion index on optrees where the only visible ops were on internal nodes. We forgot to port this fix to `SeekOpWithPatch`, which has almost the same logic just with additional work done in order to notify an `OpObserver` of changes. Add a test and fix to `SeekOpWithPatch`
=> Fix SeekOpWithPatch on optrees with only internal optrees

rust/automerge/src/query.rs
Problem: In `automerge::query::Index::change_vis` we use `-=` to subtract the width of an operation which is being hidden from the text widths which we store on the index of each node in the optree. This index represents the width of all the visible text operations in this node and below. This was causing an integer underflow error when encountering some list operations. More specifically, when a `ScalarValue::Str` in a list was made invisible by a later operation which contained a _shorter_ string, the width subtracted from the indexed text widths could be longer than the current index.
Solution: use `saturating_sub` instead. This is technically papering over the problem because really the width should never go below zero, but the text widths are only relevant for text objects where the …
=> fix: use saturating_sub when updating cached text width

README.md, flake.nix, rust/automerge/src/automerge.rs
:wave: Thanks for this great project! While getting getting set up locally I ran into a few items.
Also, the following line seems to be duplicated in `automerge.rs`:
```rust
self.history_index.insert(change.hash(), history_index);
```
=> A few setup fixes

rust/automerge-test/Cargo.toml
see https://github.com/automerge/automerge/pull/570#discussion_r1164353696
=> automerge-test 0.3.0

README.md, javascript/package.json, rust/automerge-wasm/package.json, rust/automerge/Cargo.toml
New release to fix bug in #579
=> bump @automerge/automerge to 2.0.3

javascript/test/basic_test.ts, rust/automerge-wasm/Cargo.toml, rust/automerge-wasm/src/interop.rs, rust/automerge-wasm/src/lib.rs, rust/automerge/examples/watch.rs, rust/automerge/src/autocommit.rs, rust/automerge/src/automerge.rs, rust/automerge/src/automerge/current_state.rs, rust/automerge/src/automerge/diff.rs, rust/automerge/src/lib.rs, rust/automerge/src/op_observer.rs, rust/automerge/src/op_observer/patch.rs, rust/automerge/src/op_observer/vec_observer.rs, rust/automerge/src/op_set.rs, rust/automerge/src/op_set/load.rs, rust/automerge/src/query.rs, rust/automerge/src/text_value.rs, rust/automerge/src/transaction/inner.rs, rust/automerge/src/types.rs, rust/automerge/tests/test.rs
move all logic in to a TextValue struct (a good move overall)
=> make utf16 support happen at compile time 

rust/automerge/src/op_observer/compose.rs
Noticed the duplicate call to obs2
=> Fix compose observers

javascript/src/unstable.ts
=> Re add missing `ChangeFn` type export

javascript/src/proxies.ts, javascript/test/basic_test.ts
=> js: Allow assigning Dates from the same document

rust/automerge/src/sync.rs
We want `Automerge::generate_sync_message` to only return `Some` when there is a new message to send. This allows people to call `generate_sync_message` every time anything has changed and just push the resulting message down the wire if it exists. This requires us to track whether we have already generated a message and either a) not received a message since or b) no local changes have been made. Tracking (a) is the purpose of `SyncState::in_flight`. This flag is checked whenever we generate  a sync messaage and cleared
`Automerge::receive_sync_message` whenever the received change both contains no changes and advertises that the other end has the same heads as the sender. The idea was that this is a kind of "ack" of the sent message.
The `SyncState::in_flight` flag was not being cleared …
=> Fix SyncState::in_flight logic

rust/automerge-c/CMakeLists.txt, rust/automerge-c/cmake/enum-string-functions-gen.cmake, rust/automerge-c/src/doc/mark.rs, rust/automerge-c/src/index.rs, rust/automerge-c/src/item.rs, rust/automerge-c/src/obj.rs, rust/automerge-c/src/result.rs
@orion and @alexjg, this patch fixes issue #723.
=> automerge-c: Fix 723

javascript/src/stable.ts, rust/automerge/src/autocommit.rs
Two changes:
1. Automerge.changeAt() was isolating even if the at_heads == getHeads() - this was causing the index to be unused in this case and expensive calls to clock_at() are also added.
2. AutoCommit.diff() could benefit from memoization since its often called many times in a row - this has been added - a more comprehensive version of this would be nice in the future
What I didn't do:
1. lru cache `clock_at()` - this would make all calls that use clock_at `&mut` , alternatively I was thinking of precomputing clocks while updating the hash graph and keeping them in an LRU but this would get super expensive if there were lots and lots of actors - there are several possible solutions here but I wanted to push them off to a different PR
2. address how `DocAt` could but doesn't cache it's …
=> memoize autocommit.diff() and don't isolate if I can avoid it in js

rust/automerge/src/query/nth.rs, rust/automerge/tests/test.rs
Fix Read::get_marks to respect any heads passed to it
=> fix Read::get_marks

.github/workflows/release.yaml
- trying to disable workingdirectory altogether
=> fix for c-docs release CI workflow

rust/automerge/src/query/opid.rs, rust/automerge/tests/text.rs
Problem: when splicing text at the end of a mark which is set to ExpandMark::After the patches produced when merging the splice did not contain the marks. The reason was that the `Opid` query unconditionally runs each op it encounters through the marks state machine, but when it is searching for an opid to insert after it ends up processing the operation _following_ the opid it eventually returns, which meant the marks state machine could process an end mark operation which is not actually active at the insertion poitn.
Solution: only run an op through the marks state machine if it is not greater than the op we are searching for.
Fixes: #833
=> fix expand marks not appearing in remote patches

javascript/src/stable.ts, javascript/test/change_time.ts, rust/automerge/src/transaction/commit.rs
Also, document that this value should be in milliseconds.
=> Make `ChangeOptions.time` default to current timestamp 

javascript/src/stable.ts, javascript/test/basic_test.ts
closes https://github.com/automerge/automerge/issues/995
=> fix toJS()

javascript/HACKING.md, javascript/package.json, javascript/scripts/build.mjs
=> js: fix the automerge.wasm.base64 export

rust/automerge/Cargo.toml, rust/automerge/src/op_set2/change/batch.rs, rust/automerge/src/op_set2/change/collector.rs, rust/automerge/src/op_set2/op.rs, rust/automerge/src/op_set2/op_set.rs, rust/automerge/src/op_set2/op_set/index.rs, rust/automerge/src/op_set2/op_set/mark_index.rs, rust/automerge/src/types.rs, rust/deny.toml
Automerge.length() has been optimized.  For a n=100,000 on my machine Automerge.length() went from 20ms -> 0.5ms on HEAD and 3ms at(heads)
=> optimize doc.len

javascript/test/cursors.ts
There was a test that would fail on bloom filter miss
=> fix flakey test

rust/automerge/src/lib.rs
=> rust: minor doc fix

rust/automerge/src/automerge.rs, rust/automerge/src/iter/spans.rs, rust/automerge/src/op_set2/op_set.rs, rust/automerge/src/op_set2/op_set/index.rs, rust/automerge/src/op_set2/types.rs, rust/automerge/src/patches/patch_builder.rs, rust/automerge/src/patches/patch_log.rs
Path generation is now incremental and much faster
=> remove visible_obj_paths

.github/workflows/ci.yaml, javascript/package.json, javascript/scripts/build.mjs, javascript/src/entrypoints/iife.ts, javascript/src/proxies.ts, javascript/tsconfig.json
=> js: Update @types/node from 22.16.5 to 24.0.15

javascript/src/implementation.ts, javascript/src/types.ts
https://github.com/automerge/automerge-prosemirror/blob/main/src/amToPm.ts
https://automerge.org/automerge/api-docs/js/types/Patch.html
=> export ConflictPatch, MarkPatch, UnmarkPatch

rust/automerge-wasm/src/lib.rs
=> Fix issue with TypeScript typings
